elastic/apm-agent-go

contrib/apmgin/middleware.go

Don't create a span when tracing the transaction.
It's not necessary, and not expected; only operations
within the HTTP request should result in spans being
created.
Also, allow the Tracer in Middleware to be nil,
meaning we'll use elasticapm.DefaultTracer. Also,
if DefaultTracer.Service.Framework is nil, set it
to apmgin.Framework during init().

contrib/apmgin: don't create spans; set framework

---

internal/krtext/License
internal/krtext/Readme
internal/krtext/doc.go
internal/krtext/indent.go
internal/krtext/wrap.go
internal/pretty/formatter.go

Vendor kr/text into internal/krtext

---

validation_test.go

Explicitly specify the JSON-Schema version.

Fix schema validation tests

---

module/apmsql/apmsql_test.go

Add a test which shows that we will report
exec/query on a sql.Tx. We don't currently
report the begin/commit/rollback operations.

module/apmsql: add Tx test

---

.travis.yml

- add go=stable
- allow 1.x to fail

Update Travis build matrix

---

docs/instrumenting.asciidoc

docs: add apmgocql

---

Makefile
module/apmgorm/apmgorm_test.go
module/apmgorm/context.go
module/apmgorm/doc.go
module/apmgorm/open.go
scripts/mingoversion.go

https://github.com/jinzhu/gorm/pull/2022 introduced use of sync.Map, which was introduced by Go 1.9.

module/apmgorm: require Go 1.9+

---

CHANGELOG.md
internal/apmschema/jsonschema/metadata.json
internal/apmschema/jsonschema/spans/span.json
internal/apmschema/jsonschema/transactions/transaction.json
internal/apmschema/schema.go
internal/apmschema/update.sh
tracer_test.go
validation_test.go

See individual commit messages.

More v2 unit tests

---

docs/configuration.asciidoc

Closes elastic/apm-agent-go#214

docs: add warning about environment

---

docs/index.asciidoc
docs/instrumenting.asciidoc
docs/supported-tech.asciidoc

Closes elastic/apm-agent-go#220

docs: add supported technologies page

---

docs/api.asciidoc
docs/instrumenting.asciidoc

Closes elastic/apm-agent-go#139

docs: improve context propagation docs

---

docs/index.asciidoc
docs/introduction.asciidoc

* Update agent `intro.asciidoc` per elastic/apm-dev#387
* Added a note on "best reading experience" to `index.asciidoc`

docs: update introduction

---

CHANGELOG.md
module/apmgrpc/client.go
module/apmgrpc/client_test.go
module/apmgrpc/server.go
module/apmgrpc/server_test.go
scripts/Dockerfile-testing

Propagate trace context through metadata.

module/apmgrpc: trace-context propagation

---

docs/api.asciidoc
internal/tracecontexttest/Dockerfile-harness
module/apmhttp/traceheaders.go

See also https://github.com/elastic/apm-agent-java/pull/359

Update links to w3c/trace-context

---

Jenkinsfile

* remove shared library declaration not needed (is loaded by default)
* move unit test to parallel stage (decrease about 3 min build time)
* remove schedule (not needed)
* enable ansicolor again (the bug was fixed)

Some improvements

---

Jenkinsfile

* Cleanup unused environment variables
* Cleanup not ready stages relate to integrating test (they will be added when are ready)
* Reviewed shell steps
* Reviewed Agent provision 
* Reviewed build discard settings

jenkinsfile cleanup

---

tracer_test.go

Change TestTracerErrorFlushes so that it
allows for the transaction and error to
be recorded in separate iterations.
Fixes the intermittent CI failure
> assertions.go:256:
Error Trace:	tracer_test.go:152
Error: "[]" should have 1 item(s), but has 0
Test: TestTracerErrorFlushes

Fix TestTracerErrorFlushes

---

env_test.go

Don't use os/exec.Command for this test, we can just create a new tracer which will reobtain the environment variable.

apm: tidy up test

---

Jenkinsfile

* use params also in when conditions
* grab default value params

[APM-CI][JENKINS-41929] use params for env variables default values

---

stacktrace/stacktrace_test.go

There is some variation in the stack traces between Go 1.12
and prior releases: certain runtime functions are not shown
in Go 1.12, while there is some change in the internals of
the testing package. We change the test to be less fragile,
removing the testing package code from the equation.

stacktrace: fix test for Go 1.12

---

Jenkinsfile

* trigger by a comment
* set fixed lib version

[APM-CI] trigger by a comment, set fixed lib version

---

Jenkinsfile

* Use the buildDocs step to build the documentation

[APM-CI] use the buildDocs step

---

CHANGELOG.md
docs/instrumenting.asciidoc
docs/supported-tech.asciidoc
module/apmchi/doc.go

Closes elastic/apm-agent-go#497

Add changelog and basic docs for apmchi

---

context.go
example_context_test.go

Closes elastic/apm-agent-go#450

Add examples for Transaction.Context.SetUser*

---

docs/api.asciidoc

Implements: https://github.com/elastic/apm/issues/77
~Blocked by: https://github.com/elastic/apm-server/pull/2129~

docs: add tag information

---

docs/instrumenting.asciidoc

Update missing pieces to the apmhttp module docs

---

docs/instrumenting.asciidoc
docs/supported-tech.asciidoc

docs: document apmgoredis

---

docs/configuration.asciidoc

~**Do not merge yet. Blocked by: https://github.com/elastic/kibana/pull/38577**~
Implements https://github.com/elastic/apm/issues/81

[docs][7.2] update environment config

---

CHANGELOG.md
context.go
context_test.go
docs/api.asciidoc
error.go
error_test.go
example_context_test.go
model/maps.go
model/marshal.go
model/marshal_fastjson.go
model/marshal_test.go
model/model.go
validation_test.go

Add Context.SetCustom.
Closes #579

Add support for custom context

---

docs/configuration.asciidoc
docs/metrics.asciidoc

Oops, forgot to document this one.

docs: add ELASTIC_APM_DISABLE_METRICS docs

---

Jenkinsfile

change to use the new windows-2019-immutable workers

ci: use windows-2019-immutable workers

---

metrics_test.go

Stop relying on time.Sleep as a means of driving metrics gathering, and directly wait for metrics gathering by registering a custom gatherer that signals a channel. This should improve the reliability of the test.

Improve TestTracerMetricsBuffered reliability

---

module/apmhttp/handler_test.go
span_test.go

See https://github.com/elastic/apm-agent-go/pull/625#issuecomment-527338134

Improve test reliability on macOS

---

Jenkinsfile

Closes https://github.com/elastic/apm-agent-go/issues/623
- Enable builds in MacOSX using the default `GO_VERSION`.
- Windows and MacOSX stages run in parallel now.

feat: enable build/test in MacOSX

---

transport/http.go
transport/http_test.go

transport: fix Content-Type for pprof data

---

scripts/before_install.sh

scripts: pin echo for Go 1.8/1.9

---

Jenkinsfile
scripts/jenkins/windows/install-tools.bat
scripts/jenkins/windows/uninstall-tools.bat

Caused by https://github.com/chocolatey/chocolatey.org/issues/803

ci(jenkins): Install latest golang version for Windows

---

CHANGELOG.asciidoc
internal/apmschema/jsonschema/context.json
internal/apmschema/jsonschema/message.json
internal/apmschema/jsonschema/spans/span.json
internal/apmschema/jsonschema/stacktrace_frame.json
internal/apmschema/update.sh
model/marshal_fastjson.go
model/model.go
module/apmsql/apmsql_bench_test.go
module/apmsql/apmsql_test.go
module/apmsql/conn.go
module/apmsql/stmt.go
spancontext.go

Record the number of rows affected for Exec/ExecContext calls.
Closes #578

module/apmsql: report rows affected

---

module/apmelasticsearch/client_test.go

Attempt to fix TestStatementBodyReadError, which intermittently
fails with errors like:
Expect "Get http://127.0.0.1:40849/twitter/_search: read tcp 127.0.0.1:53176->127.0.0.1:40849: use of closed network connection" to match "Get .*: Read failed"
Rather than using httptest and a real network connection, we now
use a custom RoundTripper. This also enables us to more directly
check the request body is passed through unmodified.

module/apmelasticsearch: fix flaky test

---

.gitignore
scripts/jenkins/build-test.sh

Generates test output 
Visualise the test output when running the test stage.
Closes https://github.com/elastic/apm-agent-go/issues/712

ci(jenkins): transform jUnit output for test stages

---

docs/instrumenting.asciidoc
docs/introduction.asciidoc

- change gin gonic link
- add missing import in beego module snippet
- fix wrong controller name in beego module snippet

fixing wrong documents

---

features/api_key.feature
internal/apmgodog/suitecontext.go
scripts/before_install.sh

Update to https://github.com/elastic/apm/pull/226

Update api_key.feature gherkin test

---

CHANGELOG.asciidoc
config.go
config_test.go

Enable central configuration for:
- stack_frames_min_duration
- stack_trace_limit
Closes #741

More central configuration enablement

---

error.go
error_test.go

The standard library has a built-in concept of stack traces in the runtime package. While there is no standard of how errors are tied to stack traces, the current implementation of requires either stack traces from this library directly, or from github.com/pkg/errors.
With this change, any library that implements the following interface would have their stack traces supported within APM:
```go
type runtimeStackTracer interface {
StackTrace() *runtime.Frames
}
````
The advantage to this is that now an error-handling library with stack-trace support can make itself compatible with this library without requiring go.elastic.co/apm or github.com/pkg/errors as a dependency. They only have to import the "runtime" package.
For reference, here is one such library: …

Add support for errors returning *runtime.Frames

---

model/marshal.go
model/marshal_test.go

Truncate before JSON encoding, to ensure we don't
split escape sequences. Also, take into account
Unicode by truncating based on number of runes and
not bytes.
Fixes #756

model: fix truncation of context.request.url.full

---

.ci/jobs/apm-agent-go.yml

[jjbb]: folder description is required

---

tracer_test.go
transaction.go

Surely I must be missing something, not sure what :)
Closes https://github.com/elastic/apm-agent-go/issues/809

Start cheap transactions when the tracer is not recording

---

.github/workflows/addToProject.yml

This action automatically assigns milestoned issues and new pull requests to the APM agents project

Added GitHub action to auto-assign issues to project

---

module/apmchi/go.mod
module/apmchi/go.sum

Update go module to the latest chi version.

Update chi version

---

Jenkinsfile

Enable email/slack communications when a tag release has been created.
Requires https://github.com/elastic/apm-pipeline-library/pull/976

ci: use the releaseNotification step

---

module/apmgorilla/middleware.go
module/apmgorilla/middleware_test.go

Add a WithPanicPropagation option, using apmhttp.WithPanicPropagation under the hood.
Closes #919

module/apmgorilla: add WithPanicPropagation option

---

scripts/before_install.sh

Pin to an older version of go-restful, to work around https://github.com/emicklei/go-restful/issues/467

scripts: pin go-restful to v3.4.0

---

docs/api.asciidoc
docs/configuration.asciidoc
docs/context-propagation.asciidoc
docs/custom-instrumentation.asciidoc
docs/instrumenting.asciidoc
docs/introduction.asciidoc
docs/log-correlation.asciidoc
docs/metrics.asciidoc
docs/opentracing.asciidoc
docs/troubleshooting.asciidoc

This PR cherry-picks the commits from PRs opened by @leahleahy and rebases them on the `master` branch.

documentation updates

---

internal/testdata/json-specs/service_resource_inference.json

APM agent specs automatic sync
*Changeset*
* https://github.com/elastic/apm/commit/28bb544 Adding test JSON spec for service resource auto-inference (https://github.com/elastic/apm/pull/467)

test: synchronizing json spec

---

internal/apmschema/jsonschema/metadata.json

APM agent json schema automatic sync
*Changeset*
* https://github.com/elastic/apm-server/commit/d1ebfd447 Update network connection fields (https://github.com/elastic/apm-server/pull/5671)

synchronize schema spec

---

CONTRIBUTING.md

Adds some more context to the release procedure markdown.

release: Update `CONTRIBUTING` with more context

---

scripts/before_install.sh

deps: Pin `olivere/elastic` dependency

---

.ci/jobs/defaults.yml

jjbb: exclude update-specs branches

---

CHANGELOG.asciidoc
config.go
sampler.go
sampler_test.go
tracer.go
transaction.go
transaction_test.go

Since we're making breaking changes, replace the Sampler interface with ExtendedSampler.

Replace Sampler with ExtendedSampler

---

CHANGELOG.asciidoc
context.go
context_test.go
docs/api.asciidoc
spancontext.go
spancontext_test.go

Remove the deprecated SetTag methods in v2

---

CHANGELOG.asciidoc
tracer.go
tracer_test.go

Fetch initial server version async

---

scripts/tagversion.sh

Fix `scripts/tagversion.sh` so it takes the `/v2` module path suffix into account.
Sample output after the changes:
```bash
git tag -s v2.1.0 -m v2.1.0
git tag -s module/apmnegroni/v2.1.0 -m v2.1.0
git tag -s module/apmmongo/v2.1.0 -m v2.1.0
git tag -s module/apmfasthttp/v2.1.0 -m v2.1.0
git tag -s module/apmecho/v2.1.0 -m v2.1.0
git tag -s module/apmprometheus/v2.1.0 -m v2.1.0
git tag -s module/apmrestful/v2.1.0 -m v2.1.0
git tag -s module/apmrestfulv3/v2.1.0 -m v2.1.0
git tag -s module/apmhttprouter/v2.1.0 -m v2.1.0
git tag -s module/apmot/v2.1.0 -m v2.1.0
git tag -s module/apmgoredisv8/v2.1.0 -m v2.1.0
git tag -s module/apmazure/v2.1.0 -m v2.1.0
git tag -s module/apmgopg/v2.1.0 -m v2.1.0
git tag -s module/apmgrpc/v2.1.0 -m v2.1.0
git tag -s module/apmlogrus/v2.1.0 -m v2.1.0
git tag -s …
```

scripts: fix tagversion.sh for /v2 modules

---

docs/configuration.asciidoc

Closes https://github.com/elastic/apm-agent-go/issues/1001

docs: document ELASTIC_APM_SERVER_CA_CERT_FILE

---

.github/workflows/addToAPMProject.yml

for elastic/apm-dev#810 (internal)

update ProjectNext -> ProjectV2

---

module/apmelasticsearch/client_test.go
module/apmelasticsearch/clustername.go
module/apmelasticsearch/internal/integration/elastic_integration_test.go
module/apmelasticsearch/internal/integration/olivere_integration_test.go

See https://github.com/elastic/apm/pull/688

apmelasticsearch: don't query cluster name

---

module/apmchiv5/middleware.go
module/apmchiv5/middleware_test.go

Adding an option to take advantage of panic propagation in go chi

feat: add panic propagation opt to apmchiv5

---

.ci/snapshoty.yml
.gitignore
Jenkinsfile
scripts/jenkins/package.sh

Signed-off-by: Adrien Mannocci <adrien.mannocci@elastic.co>
* Add support for daily snapshots.

Support daily snapshots

---

Jenkinsfile

The downstream dependent project will be the one pulling when a new version is available and if so then act accordingly.
https://github.com/elastic/opbeans-go/pull/81 will be the implementing it.

ci: remove release and delegate to the opbeans-go

---

tracer_test.go

Closes https://github.com/elastic/apm-agent-go/issues/1409

Fix flaky TestTracerUnsampledTransactions test

---

.ci/updatecli.d/update-json-specs.yml

Update ci job to reflect latest changes in json spec from https://github.com/elastic/apm/pull/807

ci: update json spec files

---

docs/logs.asciidoc

- Fixes a broken link
- Fixes bad UL formatting
Mentioned in [Slack](https://elastic.slack.com/archives/C0JF80CJZ/p1693567391534459) by @LucaWintergerst 
I'd like to cherry-pick this to `2.x`. (done in https://github.com/elastic/apm-agent-go/pull/1507)

Fix documentation bugs

---

.ci/updatecli/updatecli.d/update-gherkin-specs.yml
.ci/updatecli/updatecli.d/update-json-specs.yml
.ci/updatecli/updatecli.d/update-specs.yml
.github/workflows/updatecli.yml

Use signed commits:
- https://github.com/updatecli/updatecli/issues/1914

ci: updatecli signed commits

---

scripts/docker-compose-testing

This is an attempt to fix the `docker-compose` coverage failure.

Use `docker compose` rather than `docker-compose`

---

.ci/updatecli/values.d/scm.yml
updatecli-compose.yaml

<Actions>
<action id="0ae21e2aaa13536714bc1668d06619702241f3c316abeb16ea1ff024d35ee721">
<h3>deps(updatecli/policy): bump &#34;ghcr.io/elastic/oblt-updatecli-policies/apm/apm-data-spec&#34; Updatecli policy version</h3>
<details id="db669af634b75c7f298400f3b6c2aa8ba54998bac83e23d10ab4eaadc4b50ccf">
<summary>deps(updatecli/policy): bump &#34;ghcr.io/elastic/oblt-updatecli-policies/apm/apm-data-spec&#34; Updatecli version policy</summary>
<p>change detected:&#xA;&#x9;* key &#34;$.policies[0].policy&#34; updated from &#34;ghcr.io/elastic/oblt-updatecli-policies/apm/apm-data-spec:0.3.0@sha256:e7cdc38653afecaf9fad748356f545da6eb48bb9262665ff563cda974defb6f5&#34; to &#34;ghcr.io/elastic/oblt-updatecli-policies/apm/apm-data-spec:0.4.0@sha256:5ab4c0afe56d8866821644114f5442152457136892e951087cb10b2 …

deps(updatecli): bump all policies

---

.github/workflows/addToAPMProject.yml

Simlarly done in https://github.com/elastic/apm-agent-go/pull/1652
Use GH app ephemeral tokens with the required permissions.

github-actions: use GH app to manage the projects

---

docs/release-notes/index.md

We don't want to emphasize fips yet.

Remove fips mention from release notes

---

docs/release-notes/deprecations.md
docs/release-notes/known-issues.md

Updates the navigation titles for the release notes.

Updates navigation titles for release notes
