- README.md
- contrib/apmgin/apmgin_test.go
- contrib/apmsql/conn.go
- contrib/apmsql/conn_go110.go
- contrib/apmsql/conn_pre_go110.go
- contrib/apmsql/driver.go
- contrib/apmsql/driver_go110.go
- contrib/apmsql/stmt.go
- contrib/apmsql/stmt_go19.go
- contrib/apmsql/stmt_pre_go19.go
- stacktrace/context_test.go
- stacktrace/stacktrace_test.go
- trace/error.go
- transport/http_test.go
In Go 1.9 and older, os.PathError and os.SyscallError
lack the Timeout method. To simplify things, just use
the interface assertion in all error type cases.
Also, add Travis CI badge to the README.
> Fixes for Go 1.8/1.9

- trace/env.go
- trace/processor.go
- trace/tracer.go
- trace/tracer_test.go
- transport/transporttest/chan.go
- transport/transporttest/err.go
- transport/transporttest/recorder.go
- error buffering (also: make error queue size configurable)
- error/transaction processing
- client-side dropping of transactions when channel is full
- panic recovery (Tracer.Recover)
> trace: more tests

- trace/env.go
- trace/env_test.go
- trace/sampler.go
- trace/sampler_test.go
- trace/tracer.go
- trace/transaction.go
If no configuration is specified, a Tracer defaults
to sampling all transactions. Otherwise, if the
ELASTIC_APM_TRANSACTION_SAMPLE_RATE environment is
specified, it is expected to be a ratio in the range
[0,1.0], and a sampler will be constructed that
samples pseudo-randomly (with a uniform distribution)
based on that ratio.
It is possible to change the sampler after the tracer
has been constructed using its SetSampler method.
> trace: add sampling

- README.md
- trace/example_test.go
- trace/tracer.go
- trace/tracer_test.go
If Flush is called, and SendTransactions/SendErrors fails,
then we should unblock the Flush method after retrying and
succeeding.
Found with https://goreportcard.com / ineffasign.
> trace: signal Flush after retry

- contrib/apmlambda/example.go
- contrib/apmlambda/lambda.go
- env.go
- stacktrace/generate_library.bash
- stacktrace/library.go
- stacktrace/stacktrace.go
- tracer.go
- transport/transporttest/callback.go
- utils.go
Importing this package will run our own net/rpc
listener/server, and override the environment
variable such that lambda.Start will not attempt
to listen on the same port. We then proxy the
requests through to the function registered with
lambda.Start, tracing them on the way.
Still TODO: provide an apmlambda.Start function
which can be used to add the transaction to the
context provided by lambda.
> contrib/apmlambda: intercept/trace AWS lambda 

- internal/apmdebug/debug.go
- internal/pretty/License
- internal/pretty/formatter.go
- internal/pretty/pretty.go
- internal/pretty/zero.go
- transport/debug.go
- transport/default.go
Introduce ELASTIC_APM_DEBUG, which can be used to
debug the APM code. The value can be a comma-separated
list of name=value pairs. Initially, the only name
that is understood is "tracetransport"; the value
is currently ignored, but users should supply "1"
for forwards compatibility.
Setting tracetransport=1 will cause the default
transport to be wrapped so that SendTransactions
and SendErrors are logged to stderr.
> transport: ELASTIC_APM_DEBUG=tracetransport=1

- contrib/apmgorilla/LICENSE.gorillamux.txt
- contrib/apmgorilla/context.go
- contrib/apmgorilla/context_test.go
- contrib/apmgorilla/middleware.go
- contrib/apmgorilla/middleware_test.go
- contrib/apmhttp/handler.go
Introduce middleware for gorilla/mux, for tracing requests and reporting errors. We remove the regexp 
portion of variables in the path template for formatting the transaction name.
> contrib/apmgorilla: gorilla/mux middleware

- contrib/apmecho/middleware_test.go
- contrib/apmgorilla/middleware_test.go
- contrib/apmhttp/handler.go
- contrib/apmhttp/handler_test.go
- model/marshal.go
- model/marshal_test.go
- stacktrace/library.go
- tracer_test.go
- transport/transporttest/recorder.go
- refactor apmhttp so we can reuse parts of it
in middleware for frameworks/routers/toolkits
- change transport/transporttest.RecorderTransport
to record the actual payload types by marshalling
to JSON and then unmarshalling back into the same
types. This is made possible by adding unmarshal
methods for a few model types, since we simplified
most types.
> Refactor apmhttp, improve transport/transporttest

- README.md
- contrib/apmhttprouter/handler.go
- contrib/apmhttprouter/handler_test.go
- stacktrace/library.go
Introduce a handler wrapper for httprouter, for
tracing requests and reporting errors. Because
httprouter provides no way of obtaining the matched
route, the route must be passed into the WrapHandle
function as well as when registering the route
handler.
> contrib/apmhttprouter: add handler wrapper

- README.md
- contrib/apmecho/middleware_test.go
- contrib/apmgorilla/middleware_test.go
- contrib/apmgrpc/client.go
- contrib/apmgrpc/client_test.go
- contrib/apmgrpc/doc.go
- contrib/apmgrpc/packages.go
- contrib/apmgrpc/server.go
- contrib/apmgrpc/server_test.go
- contrib/apmhttp/handler_test.go
- contrib/apmhttprouter/handler_test.go
- transport/transporttest/recorder.go
Introduce contrib/apmgrpc, which contains gRPC client and server unary interceptors.
>  contrib/apmgrpc: add gRPC interceptors

- contrib/apmhttp/context.go
- contrib/apmhttp/context_test.go
- contrib/apmhttp/handler.go
- contrib/apmhttp/handler_test.go
Handle various reverse-proxy forwarding headers
when reconstructing the URL:
- Forwarded
- X-Forwarded-Host
- X-Forwarded-Proto
- X-Forwarded-Protocol
- Front-EndHttps
- X-Forwarded-Ssl
If the host is not set in a forwarding header
then the Host header value is used.
We also now use the "for" value from the Forwarded
header when determining the client address.
Closes #23
> contrib/apmhttp: improve URL reconstruction

- context.go
- contrib/apmecho/middleware.go
- contrib/apmgin/middleware.go
- contrib/apmgrpc/server.go
- contrib/apmhttp/recovery.go
- contrib/apmlambda/lambda.go
- contrib/apmsql/conn.go
- error.go
- model/marshal.go
- model/marshal_fastjson.go
- model/model.go
- tracer.go
- tracer_test.go
This is a step towards unexposing the model types from
the public API, as well as simplifying the public API.
Previously, to create an error you would call Tracer.NewError,
and then call either its SetLog or its SetException methods.
Now, instead you just call Tracer.NewError(error) or
Tracer.NewErrorLog(ErrorLogRecord). Additionally, you would
previously call SetLogStacktrace or SetExceptionStacktrace.
Now you just call SetStacktrace, and it is routed to the
correct place depending on how the error was constructed.
Error's previously embedded model.Error has been renamed
to "model" (i.e. unexposed), and various fields have been
added to Error for customising the error (ID, Culprit, etc.)
As a result, changes have been made to how we set the
exception details: if an error implements Type …
> Revise errors interface

- contrib/apmlambda/lambda.go
- error.go
- error_test.go
- stacktrace.go
- stacktrace/doc.go
- stacktrace/frame.go
- stacktrace/stacktrace.go
- stacktrace/stacktrace_test.go
- tracer.go
- tracer_test.go
- transaction.go
Introduce stacktrace.Frame, a distilled
version of runtime.Frame, with only the
information we care about. Errors may
now implement
type interface {
StackTrace() []stacktrace.Frame
}
as an alternative to pkg/errors, rather
than directly referencing the model
stacktrace frame type. This moves us a
step closer to not exposing the model
types in any if the public/stable API.
Stacktrace functions have been changed
to append to provided slices, enabling
memory reuse.
> all: introduce and use stacktrace.Frame

- contrib/apmhttp/context.go
- contrib/apmhttp/context_test.go
- contrib/apmhttp/handler.go
- contrib/apmhttp/handler_bench_test.go
- contrib/apmhttp/requestname.go
- contrib/apmhttp/requestname_go19.go
- error.go
- internal/apmhttputil/forwarded.go
- internal/apmhttputil/forwarded_test.go
- internal/apmhttputil/remoteaddr.go
- internal/apmhttputil/remoteaddr_test.go
- internal/apmhttputil/url.go
- internal/apmhttputil/url_test.go
- internal/fastjson/writer.go
- model/marshal.go
- model/marshal_fastjson.go
- model/marshal_test.go
- model/model.go
- tracer.go
- transaction.go
- apmhttp: move some HTTP context functions to internal/apmhttputil
- apmhttp: change responseWriter to not cache the CloseNotify or Flush methods, as that allocates more memory.
- apmhttp: use strings.Builder (go1.10+) or copy instead of fmt.Sprintf when formatting HTTP transaction names
- apmhttputil: pre-canonicalize HTTP headers (X-Real-IP -> X-Real-Ip) to avoid repeated string copies
- {apmhttputil,model}: format the full URL in the MarshalFastJSON method, to avoid allocating a string only to be copied into the buffer later.
- {elasticapm,model}: store time.Time in model objects, format using AppendFormat
- {elasticapm,model}: make Transaction.SpanCount a non-pointer field using fastjson's omitempty "isZero" method support
There's more to come, but they are more invasive, and change …
> all: various internal optimizations

- contrib/apmsql/apmsql_bench_test.go
- contrib/apmsql/apmsql_go110_test.go
- contrib/apmsql/apmsql_test.go
- contrib/apmsql/conn.go
- contrib/apmsql/driver.go
- contrib/apmsql/driver_go110.go
- contrib/apmsql/stmt.go
- spancontext.go
- transaction.go
Add a SpanContext type, embedded in Spans, and unexpose the model.Span field of Span.
Also, add some basic tests for contrib/apmsql.
Partially addresses #46
>  elasticapm: introduce/use SpanContext

- contrib/apmgin/bench_test.go
- contrib/apmgin/middleware.go
Avoids an additional allocation for each transaction.
>  contrib/apmgin: precompute route transaction names

- env_test.go
- error_test.go
- tracer.go
- tracer_test.go
- utils.go
When specifying the service name via environment
variable, it is now sanitized; invalid characters
are replaced with '_'. When creating a tracer
with NewTracer with an explicitly specified
service name, that service name must be valid,
or an error will be returned. Otherwise, the
sanitized executable name will be used as the
service name.
Closes #32
> elasticapm: validate/sanitize service name

- README.md
- env.go
- env_test.go
- sanitizer.go
- sanitizer_test.go
- tracer.go
Sanitize cookies and POST form fields by matching
their names against a configurable regular expression.
By default, we match against:
`(?i:password|passwd|pwd|secret|.*key|.*token|.*session.*|.*credit.*|.*card.*)`
The pattern can be overridden by specifying the
environment variable ELASTIC_APM_SANITIZE_FIELD_NAMES.
The value is treated as a regular expression, and
is wrapped as `(?i:<pattern>)` to match case-insensitively
by default. If a key should be matched case-sensitively,
the flag can be unset with the syntax `(?-i:<pattern>)`.
Closes #21
> elasticapm: sanitize cookies and POST form fields

- .travis.yml
- Makefile
- context.go
- model/model.go
Add "go vet" and "golint" to the precheck make target. See https://github.com/elastic/apm-agent-go/pull/60.
> Add vet and golint to prechecks

- README.md
- capturebody.go
- context.go
- contrib/apmecho/middleware.go
- contrib/apmecho/middleware_test.go
- contrib/apmgin/middleware.go
- contrib/apmhttp/handler.go
- contrib/apmhttp/handler_test.go
- contrib/apmhttp/recovery.go
- contrib/apmhttprouter/handler.go
- env.go
- env_test.go
- error.go
- model/marshal.go
- tracer.go
- transaction.go
If ELASTIC_APM_CAPTURE_BODY is set, then HTTP modules will capture the request body, either as a raw string or as a map of form data.
Closes #58
> Capture HTTP bodies

- README.md
- contrib/apmecho/middleware.go
- contrib/apmgin/bench_test.go
- contrib/apmgin/middleware.go
- contrib/apmlambda/lambda.go
- env.go
- tracer.go
- utils.go
Stop exposing the full service model in the
tracer - expose only the service name, version,
and environment instead. It is now no longer
possible to override the agent, language or
runtime; and it is no longer possible to set
the framework at all.
Framework is problematic because it doesn't
necessarily apply to all transactions, and
there's no way to attach the information at
the transaction level. So instead of including
it in a problematic state, we'll drop support
initially and work updates into the API and
server, and then reintroduce it later.
See https://github.com/elastic/apm-agent-go/issues/69
> all: drop support for Service.Framework

- .travis.yml
- appveyor.yml
- context.go
- error.go
- internal/apmhttputil/url.go
- internal/apmstrings/truncate.go
- internal/apmstrings/truncate_test.go
- model/marshal.go
- model/marshal_fastjson.go
- model/marshal_test.go
- model/model.go
- transaction.go
- utils.go
- validation_test.go
Truncate strings we send so we don't cause validation errors. The alternative is to reject the entire payload, which is a bit drastic.
Also, if an error log or exception message is empty, set it to "[EMPTY]" instead. The message is required.
Fix a bug found in the "full" URL truncation logic.
Closes https://github.com/elastic/apm-agent-go/issues/48
> Truncate strings to avoid validation errors

- contrib/apmecho/middleware.go
- contrib/apmecho/middleware_test.go
- contrib/apmgin/middleware.go
- contrib/apmgin/middleware_test.go
- contrib/apmgorilla/middleware_test.go
- contrib/apmhttp/context.go
- contrib/apmhttp/context_test.go
- contrib/apmhttp/handler.go
- contrib/apmhttp/handler_test.go
- contrib/apmhttprouter/handler_test.go
Update apmhttp (and dependent modules) to format
the transaction result like "HTTP 2xx", "HTTP 4xx",
etc. This is how other agents are doing it, and
what the UI expects.
Closes #66
> contrib/apmhttp: update HTTP result format

- README.md
- env.go
- env_test.go
- tracer.go
- tracer_test.go
- transaction.go
If a span's duration exceeds a configurable threshold
(ELASTIC_APM_SPAN_FRAMES_MIN_DURATION, defaults to 5ms),
then we will capture a stacktrace for that span when its
Done method is called. If the span's stacktrace has
already been set, then it will not be replaced.
Closes #56
> elasticapm: capture span stack frames

- transport/api.go
- transport/http_test.go
Transports aren't required to be safe for concurrent use,
so document that and drop the tests. They were causing
"go test -race" to fail.
> transport: drop concurrency tests

- README.md
- env_test.go
- module/apmecho/middleware.go
- module/apmecho/middleware_test.go
- module/apmgin/bench_test.go
- module/apmgin/middleware.go
- module/apmgin/middleware_test.go
- module/apmgorilla/middleware.go
- module/apmgorilla/middleware_test.go
- module/apmhttp/handler.go
- module/apmhttp/handler_bench_test.go
- module/apmhttp/handler_test.go
- module/apmhttp/recovery.go
- module/apmhttprouter/handler.go
- module/apmhttprouter/handler_test.go
- sanitizer_test.go
All modules are updated to use functional options
where we provide a Wrap or Middleware method. The
end result is that none of the modules require
passing in a nil Tracer to use the default.
Also:
- apmhttp now recovers panics by default
- apmhttprouter's WrapHandler is now called Wrap
Closes #77
> module/...: update all to use functional options

- README.md
... and drop the warning, we want people to start using this in anger now.
> Add survey link to README; s/pre-alpha/alpha/

- docs/configuration.asciidoc
- env.go
- env_test.go
- module/apmecho/middleware.go
- module/apmgin/middleware.go
- module/apmgrpc/server.go
- module/apmhttp/handler.go
- module/apmhttp/handler_test.go
- module/apmhttprouter/handler.go
- tracer.go
If the tracer is inactive, then no transactons or errors will
be sent to the server; the tracer goroutine is never started.
The tracer grows an "Active() bool" method, which modules can
use to check if they should bail early.
Also, add a "RequestIgnorer" option to apmhttp, so clients can
programatically ignore certain requests.
Closes #86
> Support ELASTIC_APM_ACTIVE

- module/apmecho/middleware.go
- module/apmgin/middleware.go
- module/apmhttp/handler.go
- module/apmhttprouter/handler.go
- transport/http.go
net/http.Request.WithContext has an unfortunate code
path which copies the *net.URL within the request,
which causes an allocation. We don't need (or want)
this behaviour, we just want to set the new context.
To avoid the allocation we introduce a new function
apmhttp.RequestWithContext, which avoids the copy by
clearing the request's URL during the WithContext
call.
Also, apmhttp.SetTransactionContext has been updated
slightly to drop the ResponseWriter parameter. The
Response type grows a Headers field, which is used
instead.
>  module/...: introduce apmhttp.RequestWithContext

- stacktrace/generate_library.bash
- stacktrace/library.go
- stacktrace/library_test.go
When classifying packages, always consider packages whose paths contain "/vendor/" to be libraries.
Closes #89
> stacktrace: vendored packages are libraries

- docs/api.asciidoc
- docs/instrumenting.asciidoc
- example_test.go
- gocontext.go
- gofuzz.go
- module/apmgrpc/client.go
- module/apmgrpc/server_test.go
- module/apmsql/apmsql_bench_test.go
- module/apmsql/conn.go
- module/apmsql/driver_go110.go
- module/apmsql/stmt.go
- transaction.go
Transaction.StartSpan and elasticapm.StartSpan now
always return non-nil, even if the transaction is nil.
This simplifies callsites so they don't have to nil
checking of spans.
> elasticapm: StartSpan always returns non-nil

- module/apmgorilla/middleware.go
- module/apmhttp/handler.go
- module/apmhttp/handler_test.go
- module/apmhttp/requestname.go
- module/apmhttp/requestname_go19.go
(And other similar renamings.)
This is in preparation for https://github.com/elastic/apm-agent-go/issues/98, which will involve introducing client-side span tracing options.
> module/apmhttp: rename Option to ServerOption

- docs/instrumenting.asciidoc
- module/apmhttp/client.go
- module/apmhttp/client_bench_test.go
- module/apmhttp/client_test.go
- module/apmhttp/doc.go
- module/apmhttp/handler.go
- module/apmhttp/handler_bench_test.go
- module/apmhttp/requestname.go
- module/apmhttp/requestname_go19.go
Introduce WrapClient and WrapRoundTripper,
which create spans for client-side requests.
Spans are created only if the request context
contains a transaction.
Closes #98
> module/apmhttp: introduce client span tracing

- docs/api.asciidoc
- docs/instrumenting.asciidoc
- env_test.go
- error.go
- example_test.go
- gocontext.go
- gofuzz.go
- module/apmecho/middleware.go
- module/apmgin/middleware.go
- module/apmgrpc/client.go
- module/apmgrpc/client_test.go
- module/apmgrpc/server.go
- module/apmgrpc/server_test.go
- module/apmhttp/client.go
- module/apmhttp/client_test.go
- module/apmhttp/handler.go
- module/apmhttprouter/handler.go
- module/apmlambda/lambda.go
- module/apmsql/apmsql_test.go
- module/apmsql/conn.go
- module/apmsql/driver_go110.go
- span.go
- tracer_test.go
- transaction.go
- validation_test.go
Rename Span.Done and Transaction.Done methods to End. Drop the time.Duration parameter, and instead expose a time.Duration field on the types, initialised to a negative value. If it is negative at the time End is called, set it to the time elapsed since the Timestamp field.
Also, rename Span.Start to Span.Timestamp to be consistent with the Transaction type.
Closes #104 
Closes #105
> elasticapm: Done->End, Span.Start->Timestamp

- transaction.go
TransactionOption now accepts an unexposed
transactionOptions struct. TransactionOptions
must be defined within the elasticapm package,
so we can make assumptions about the state of
the transaction object after the options have
been applied. This will also give us a way of
specifying options like overriding the sampler,
which is not part of the transaction object.
> elasticapm: change TransactionOption signature

- docs/configuration.asciidoc
- docs/instrumenting.asciidoc
- env.go
- env_test.go
- module/apmecho/middleware.go
- module/apmgin/middleware.go
- module/apmgrpc/server.go
- module/apmhttp/handler.go
- module/apmhttprouter/handler.go
- tracer.go
- tracer_test.go
- transaction.go
Drop the ability to ignore transactions, and
the Transaction.Ignored() method. These are
causing complications around adding support
for OpenTracing. It's also just more efficient
to keep the filtering outside of transaction
creation, so we don't have to create garbage
that is immediately thrown away. Instrumentation
modules should be responsible for that.
> elasticapm: drop Transaction.Ignored()

- sender.go
- span.go
- transaction.go
As it says on the tin. The name and type can
be changed any time before the End method is
invoked.
Closes #110
> Expose Name, Type fields of Span, Transaction

- docs/contributing.asciidoc
- docs/index.asciidoc
- docs/introduction.asciidoc
Use the shared attributes provided
by elastic/docs for linking to other
product docs, forums, etc.
Requires https://github.com/elastic/docs/pull/369
> docs: use shared attributes

- README.md
- doc.go
- docs/index.asciidoc
- version.go
This is the first release we consider to be production-ready. We do not
anticipate significant breaking changes to the API, but we do not rule
it out entirely.
> Version 0.4.0

- docs/configuration.asciidoc
- transport/default.go
- transport/default_test.go
- transport/http.go
- transport/http_test.go
If ELASTIC_APM_SERVER_URL is not specified,
default to http://localhost:8200 like the
other agents.
Fixes #121
> transport: default ELASTIC_APM_SERVER_URL

- transport/default_test.go
- transport/http_test.go
Use httptest rather than http.Server, to avoid
issues relating to servers advertising support
for keep-alive and closing idle connections.
> transport: fix tests

- transport/http.go
- transport/http_test.go
Add Transport.SetUserAgent method, which may be
used to override the default User-Agent header.
Fixes #118
> transport: add method for setting User-Agent

- go.mod
- go.sum
We will probably want to add additional vgo modules for the instrumentation modules, that'll be done as a followup.
Closes https://github.com/elastic/apm-agent-go/issues/83
> Add vgo bits

- .travis.yml
- appveyor.yml
- gofuzz.go
- internal/apmschema/jsonschema/context.json
- internal/apmschema/jsonschema/errors/error.json
- internal/apmschema/jsonschema/errors/payload.json
- internal/apmschema/jsonschema/metrics/metric.json
- internal/apmschema/jsonschema/metrics/payload.json
- internal/apmschema/jsonschema/metrics/sample.json
- internal/apmschema/jsonschema/process.json
- internal/apmschema/jsonschema/request.json
- internal/apmschema/jsonschema/service.json
- internal/apmschema/jsonschema/sourcemaps/payload.json
- internal/apmschema/jsonschema/stacktrace_frame.json
- internal/apmschema/jsonschema/system.json
- internal/apmschema/jsonschema/transactions/mark.json
- internal/apmschema/jsonschema/transactions/payload.json
- internal/apmschema/jsonschema/transactions/span.json
- internal/apmschema/jsonschema/transactions/transaction.json
- internal/apmschema/jsonschema/user.json
- internal/apmschema/schema.go
- internal/apmschema/update.sh
- model/gofuzz.go
- validation_test.go
Vendor the JSON schema in internal/apmschema;
parse them when importing that package. This
is intended for testing only; all tests have
been updated to use this.
> internal/apmschema: vendor JSON schema

- docs/instrumenting.asciidoc
- module/apmhttprouter/router.go
- module/apmhttprouter/router_test.go
Add a Router type and accompanying New
constructor function, mirroring the
httprouter API. New takes options just
like Wrap does. Added routes will be
instrumented, and options will be passed
onto the Wrap method internally.
Closes #138
> module/apmhttprouter: add Router and New

- CHANGELOG.md
- context.go
- context_test.go
- docs/api.asciidoc
- model/marshal.go
- model/marshal_fastjson.go
- model/marshal_test.go
- model/model.go
- validation_test.go
Add methods to Transaction.Context for setting the user ID/username/email. Remove the ability to set a numeric user ID.
> Transaction.Context methods for setting user IDs

- module/apmgocql/apmgocql_test.go
Tests are failing on Jenkins due to slow machines,
and the delta being exceeded. Increase allowance.
> module/apmgocql: increase time delta in test

- builtin_metrics.go
- internal/apmschema/jsonschema/context.json
- internal/apmschema/jsonschema/metrics/metric.json
- internal/apmschema/jsonschema/metrics/sample.json
- internal/apmschema/jsonschema/transactions/mark.json
- internal/apmschema/jsonschema/transactions/transaction.json
- metrics.go
- metrics_test.go
- model/marshal.go
- model/marshal_fastjson.go
- model/marshal_test.go
- model/model.go
- module/apmgometrics/gatherer.go
- module/apmgometrics/gatherer_test.go
- module/apmprometheus/gatherer.go
- module/apmprometheus/gatherer_test.go
- validation_test.go
For the initial implementation of metrics, we won't support specifying metric types or units, nor will we support summary metrics (in the API, schema, or wire protocol; bridges may still transform and send them). This is in line with existing metrics in the Elastic Stack (namely Metricbeat), and how they are today interpreted in Kibana.
Also, rename some of the builtin metrics to align with Metricbeat.
> Pare back the metrics API

- CHANGELOG.md
- docs/configuration.asciidoc
- env.go
- internal/apmconfig/duration.go
- internal/apmconfig/env.go
- internal/apmconfig/env_test.go
- transport/http.go
- transport/http_test.go
Defaults to 30s, but can be overridden. If set to a non-positive value, timeout is disabled.
Closes elastic/apm-agent-go#155
> Add ELASTIC_APM_SERVER_TIMEOUT config

- CHANGELOG.md
- docs/configuration.asciidoc
- module/apmecho/middleware.go
- module/apmgin/middleware.go
- module/apmgorilla/middleware.go
- module/apmhttp/client.go
- module/apmhttp/handler.go
- module/apmhttp/ignorer.go
- module/apmhttp/ignorer_test.go
- module/apmhttprouter/handler.go
Add support for ignoring requests with URLs matching the
regular expression specified in ELASTIC_APM_IGNORE_URLS.
Ignore requests are executed as normal, they just won't
be reported to Elastic APM.
Closes #154
> module/apmhttp: support ELASTIC_APM_IGNORE_URLS

- CHANGELOG.md
- module/apmsql/apmsql_go110_test.go
- module/apmsql/apmsql_test.go
- module/apmsql/conn.go
- module/apmsql/stmt.go
We were passing the (initial nil) error value
to finishSpan by mistake. Pass a pointer to the
result error var instead, to capture the final
value.
Fixes #159
> module/apmsql: fix error capture

- .travis.yml
Pass "-T" to docker-compose run to ensure stdout
and stderr are separated, otherwise coverage.txt
gets messed up.
> .travis.yml: fix coverage.txt output from docker

- scripts/test_coverage.sh
When running coverage tests, record coverage for
all packages under apm-agent-go. This will give
us the total coverage for all packages regardless
of where the tests lie.
> scripts: add -coverpkg to test_coverage.sh

- CHANGELOG.md
- module/apmhttp/handler.go
- transaction.go
Introduce Tracer.StartTransactionOptions, a variant
of Tracer.StartTransaction which accepts a third
parameter of type TransactionOptions. This replaces
the TransactionOption functional options; StartTransaction
no longer accepts variadic arguments.
The purpose of this is to avoid allocations due to
closures in hot code paths, such as starting transactions
in http middleware, where setting trace context will
be commonplace.
> elasticapm: introduce StartTransactionOptions

- CHANGELOG.md
- context.go
- model/marshal.go
- model/marshal_fastjson.go
- model/marshal_test.go
- model/model.go
- module/apmhttp/client.go
- module/apmhttp/client_test.go
- spancontext.go
In the elasticapm package, we introduce a new SpanContext.SetHTTPRequest method which records the URL of an outgoing HTTP request in span context, and later add it to the span model object. Finally we modify the apmhttp client instrumentation to make use of this.
Closes elastic/apm-agent-go#171
>  module/apmhttp: set client request URL

- CHANGELOG.md
- module/apmhttp/client.go
- module/apmhttp/handler.go
- module/apmhttp/traceheaders.go
- module/apmot/context.go
- module/apmot/doc.go
- module/apmot/example_test.go
- module/apmot/harness_test.go
- module/apmot/span.go
- module/apmot/tracer.go
- module/apmot/tracer_test.go
- scripts/Dockerfile-testing
Implement an OpenTracing tracer on top of the
core API. Root spans create transactions, and
child spans create spans or transactions,
depending on whether or not the parent is
remote.
Neither baggage nor logging are supported,
nor is the binary propagation format. We use
the (draft) W3C Trace-Context, for which there
is not yet a binary format.
There is a bug in the span context which we
cannot fix until spans are top-level objects,
which will happen with the v2 API. We will
revisit this when the v2 API is supported. The
bug is unlikely to affect anyone, since it will
only occur if you attempt to use span context
after the span has been finished/ended.
In line with the Elastic APM Java agent's
implementation, we support several custom tags:
- type (transaction or span type)
- user.id, …
>  module/apmot: initial tracer implementation

- module/apmhttp/traceheaders_test.go
- tracecontext.go
- tracecontext_test.go
- transaction.go
Update TraceContext options to store two bits: requested and recorded.
Closes #176
> Update TraceContext options

- internal/ringbuffer/buffer.go
- internal/ringbuffer/buffer_test.go
- modelwriter.go
- tracer.go
- tracer_test.go
Update internal/ringbuffer, extending the header
to include a single byte tag as well as the data
size. Add an "Evicted" function field to Buffer,
which will be called with the block header for
evicted blocks.
We use this in the tracer to update the dropped
stats when the buffer is full. We also now more
accurately update the sent stats when extracting
from the buffer (writing to zlib), rather than when
writing to the buffer.
> Record event type in ring buffer header

- builtin_metrics.go
- docs/configuration.asciidoc
- internal/apmdebug/debug.go
- tracer.go
Change ELASTIC_APM_DEBUG to control logging.
If you set ELASTIC_APM_DEBUG="log=1", then
the tracer will log messages to stderr as
well as to a logger specified via SetLogger.
Also, don't update "sent" stats until the
request has completed successfully. If the
request fails, we don't increment the stats;
the events may have been sent, or they may
have been lost. We instead increment the
errors.send_stream counter.
> ELASTIC_APM_DEBUG controls logging

- .appveyor.yml
- module/apmgocql/apmgocql_test.go
- module/apmgocql/doc.go
- module/apmgocql/observer.go
- module/apmgocql/signature.go
- module/apmgocql/signature_test.go
gocql now requires Go 1.9, due to its use of math/bits.
>  module/apmgocql: require Go 1.9+

- .github/ISSUE_TEMPLATE/Bug_report.md
- .github/ISSUE_TEMPLATE/Feature_request.md
- .github/ISSUE_TEMPLATE/Question.md
Add GitHub issue templates. Copied from apm-agent-java with minor changes.
Closes #192
> .github: add issue templates

- modelwriter.go
- module/apmgocql/apmgocql_test.go
- module/apmgocql/doc.go
- module/apmgocql/observer.go
- module/apmgocql/signature.go
- module/apmgocql/signature_test.go
- span.go
Until elastic/apm-server#1340 is resolved,
keep setting span.start. The way we set it
is unsound, assuming the transaction timestamp
cannot change after construction. If we do
not go ahead with making span.start optional,
we'll have to adjust the API.
> elasticapm: set model.Span.Start

- model/marshal.go
- model/marshal_fastjson.go
- model/marshal_test.go
- model/model.go
- modelwriter.go
- module/apmot/context.go
- module/apmot/doc.go
- module/apmot/harness_test.go
- module/apmot/span.go
- module/apmot/tracer.go
- module/apmot/tracer_test.go
- span.go
- span_test.go
- transaction.go
Introduce Tracer.StartSpan, which takes a transaction ID
and parent span/transaction trace context. This method
should only be used when there is no active transaction.
Also introduce Transaction.StartSpanOptions, which takes
a SpanOptions containing an optional start timestamp and
optional parent span trace context. This may be used over
the StartSpan method if the parent span is already ended.
We leave the existing StartSpan method for its simplicity.
In module/apmot, we use Tracer.StartSpan if the transaction
has been ended. Otherwise, we use Transaction.StartSpanOptions,
and pass in the trace context of the parent span or transaction;
this means we no longer pass a parent span object into StartSpan,
so we don't care about whether or not it has been finished.
Finally, we introduce …
> module/apmot: don't hold ended transactions/spans

- CHANGELOG.md
- error.go
- error_test.go
- version.go
When checking if we should automatically set the
stacktrace for a new error, check the length of
the stacktrace slice is zero rather than checking
that it is nil. The slice may be non-nil for a
reused error object.
> Check reused error stacktrace slice correctly

- CHANGELOG.md
- gocontext.go
- model/model.go
- modelwriter.go
- module/apmgocql/observer.go
- module/apmot/context.go
- module/apmot/span.go
- module/apmot/tracer.go
- span.go
- span_test.go
- transaction.go
If you want to specify the timestamp for a
transaction or span, you must now supply those
when constructing them via TransactionOptions
or SpanOptions. This enables us to store the
transaction timestamp on the span object, so
we can report the transaction timestamp and
calculate the start offset.
Closes #207
> Unexpose Timestamp from Transaction and Span

- env.go
- env_test.go
- internal/apmconfig/duration.go
- internal/apmconfig/env.go
- internal/apmconfig/env_test.go
- transport/http.go
Stop using time.ParseDuration, and implement our own, more constrained parser.
Closes elastic/apm-agent-go#189
> Require unit for durations (ms, s, or m)

- CHANGELOG.md
- tracer.go
- utils.go
- utils_test.go
When backing off due to transport errors,
add +/-10% to the grace period to prevent
agents synchronising their retries.
> Add jitter to grace period

- CHANGELOG.md
- model/marshal_fastjson.go
- model/model.go
- module/apmot/span.go
- module/apmot/tracer_test.go
- spancontext.go
Add elasticapm.SpanContext.SetTags method.
Closes #147
> Add support for span tags

- module/apmhttp/client.go
Remove some checks for distributed tracing which
are no longer required with v2, since distributed
tracing is always on with v2.
> module/apmhttp: remove unnecessary DT checks

- modelwriter.go
- transport/transporttest/recorder.go
- validation_test.go
The server previously expected "metric", and we were wrongly writing it as "metrics". In v2, it will be changed to "metricset" - see https://github.com/elastic/apm-server/pull/1359.
> Change name of "metric" stream object

- CHANGELOG.md
- module/apmgorm/context.go
- version.go
The Span.End() call should come after the calls
to CaptureError, which will refer to the span.
Bump version to 0.5.2.
Fixes #229
>  module/apmgorm: fix premature Span.End()

- error.go
- error_test.go
- model/marshal_fastjson.go
- model/marshal_test.go
- model/model.go
- modelwriter.go
Same format as trace ID. This is due to the
fact that errors may be reported independently
of traces.
Closes elastic/apm-agent-go#225
> Change error.id to 128-bit

- CHANGELOG.md
- docs/opentracing.asciidoc
- gocontext.go
- internal/apmcontext/context.go
- module/apmot/context.go
- module/apmot/noop.go
- module/apmot/span.go
- module/apmot/tracer.go
- module/apmot/tracer_test.go
- module/apmot/wrapper.go
Introduce an internal package which is used
instead of using context.WithValue/context.Value
directly. By default those functions are used,
but when apmot is imported, it overrides their
use with the opentracing context functions,
wrapping all transactions and spans such that
they implement the opentracing.Span API.
> Decouple elasticapm/opentracing

- CHANGELOG.md
- context.go
- module/apmecho/middleware.go
- module/apmecho/middleware_test.go
- module/apmgin/middleware.go
- module/apmgin/middleware_test.go
- module/apmgorilla/middleware_test.go
- module/apmhttp/handler.go
- module/apmhttp/handler_test.go
- module/apmhttp/recovery.go
- module/apmhttprouter/handler.go
- module/apmhttprouter/handler_test.go
We no longer set context.response.headers_sent or finished.
These may make sense for other languages/runtimes, but not for
Go, where a response is either guaranteed, or lack of response
cannot be observed.
Also:
- set other response context on transactions and errors consistently
- stop setting custom context in apmgin
Closes #208
>  Drop Context.SetHTTPResponse{HeadersSent,Finished}

- transaction.go
- transaction_test.go
- Only sample for root transactions.
- Sample if the parent requested, disregard whether or not the parent may have recorded.
Closes #241
> Update trace-context options handling

- env.go
- sampler.go
- sampler_test.go
- span_test.go
- transaction.go
- transaction_test.go
Sampler now accepts a TraceContext, rather than
Transaction. NewRatioSampler returns Sampler,
and the concrete type has been unexported.
Additionally, the ratio sampler now bases its
decision on the span (transaction) ID, rather
than computing another random number. This
also avoids synchronisation on an RNG mutex.
> Update Sampler API

- capturebody.go
- context.go
- error.go
- modelwriter.go
- spancontext.go
- utils.go
- validation_test.go
All strings we craft and transmit to the server are now truncated to either 1024 runes (for keywords) or 10000 runes (for non-keywords). This does not cover "custom" context, since that is opaque to the agent code, but it does cover tags.
Closes #187
> [v2] Truncate non keywords

- docs/instrumenting.asciidoc
- docs/supported-tech.asciidoc
- module/apmredigo/conn.go
- module/apmredigo/conn_test.go
- module/apmredigo/doc.go
- module/apmredigo/integration_test.go
- scripts/Dockerfile-testing
- scripts/docker-compose-testing.yml
We introduce module/apmredigo, which provides
top-level function for calling redis.Conn.Do
with a context, a la ctxhttp.Do. apmredigo also
provides a function (ContextConn) for binding a
redis.Conn to a given context, diverting Do calls
to the aforementioned Do-with-context function.
Send and Receive are not instrumented. For now,
spans should be created for the higher-level
operations in which they are used (pub/sub,
transactions, etc.)
Closes #35
> module/apmredigo: introduce redigo instrumentation

- context.go
- context_test.go
- model/marshal_fastjson.go
- model/marshal_test.go
- model/model.go
- module/apmecho/middleware.go
- module/apmecho/middleware_test.go
- module/apmgin/middleware.go
- module/apmgin/middleware_test.go
- module/apmgrpc/server.go
- module/apmgrpc/server_test.go
- utils.go
Add a method for instrumentation to set the framework information for a transaction or error context.
At the time of writing, the server merges back-to-front such that service-level overrides event-level, but that's OK for our purposes as we only set framework info in the transaction/error level, and never in service-level metadata.
Update apmecho, apmgin, and apmgrpc server middleware to set the framework info.
Closes #69
>  elasticapm: add Context.SetFramework

- span.go
- utils.go
- utils_linux_test.go
- utils_other.go
- utils_test.go
Use go-sysinfo on non-Linux systems. Could use it on Linux too, but that would incur more overhead for the usual case.
Closes #254
> Implement currentProcessTitle for non-Linux

- CHANGELOG.md
- internal/apmschema/jsonschema/errors/common_error.json
- internal/apmschema/jsonschema/errors/v2_error.json
- internal/apmschema/jsonschema/metadata.json
- internal/apmschema/jsonschema/metricsets/common_metricset.json
- internal/apmschema/jsonschema/metricsets/sample.json
- internal/apmschema/jsonschema/metricsets/v2_metricset.json
- internal/apmschema/jsonschema/spans/common_span.json
- internal/apmschema/jsonschema/spans/v2_span.json
- internal/apmschema/jsonschema/timestamp_epoch.json
- internal/apmschema/jsonschema/transactions/common_transaction.json
- internal/apmschema/jsonschema/transactions/v2_transaction.json
- internal/apmschema/schema.go
- internal/apmschema/update.sh
- model/marshal.go
- model/marshal_fastjson.go
- model/marshal_test.go
- model/model.go
- modelwriter.go
- module/apmot/tracer.go
- span.go
- span_test.go
Spans are now reported with timestamps rather than offsets relative to the transaction start time. The timestamp is still calculated based on the transaction timestamp using the monotonic clock. All timestamps are now reported as microseconds since the Unix epoch.
Closes #240
> [v2] Update timestamps to usec since epoch

- CHANGELOG.md
- docs/configuration.asciidoc
- env.go
- env_test.go
- internal/apmconfig/env.go
- internal/apmconfig/env_test.go
- internal/apmconfig/list.go
- internal/apmconfig/wildcards.go
- internal/wildcard/doc.go
- internal/wildcard/matcher.go
- internal/wildcard/matcher_test.go
- internal/wildcard/matchers.go
- modelwriter.go
- module/apmhttp/ignorer.go
- module/apmhttp/ignorer_test.go
- sanitizer.go
- tracer.go
Implement wildcard matching, and update `ELASTIC_APM_SANITIZE_FIELD_NAMES` and `ELASTIC_APM_IGNORE_URLS` to use that instead of regular expressions. This will bring is in alignment with the Java agent.
> ELASTIC_APM_SANITIZE_FIELD_NAMES and ELASTIC_APM_IGNORE_URLS now use wildcard matching

- module/apmhttp/traceheaders_test.go
- span.go
- tracecontext.go
- tracecontext_test.go
- transaction.go
- transaction_test.go
Requested has been dropped from trace-context, following suit.
Closes elastic/apm-agent-go#262
> Drop "requested" option from trace context

- doc.go
The canonical import path is now go.elastic.co/apm.
Since there are internal packages in use, it's not
possible to use any other package path.
> apm: set canonical import path

- module/apmgrpc/server.go
- module/apmgrpc/server_test.go
- module/apmlambda/example.go
- module/apmlambda/lambda.go
- scripts/Dockerfile-testing
Custom context is meant for user code, not for
canned instrumentation. We'll extend the schema
later to satisfy RPC and FaaS.
Closes elastic/apm-agent-go#251
> module/...: stop setting custom context

- CHANGELOG.md
- docs/instrumenting.asciidoc
- docs/supported-tech.asciidoc
- module/apmrestful/doc.go
- module/apmrestful/filter.go
- module/apmrestful/filter_example_test.go
- module/apmrestful/filter_test.go
- module/apmrestful/route.go
- module/apmrestful/route_test.go
- scripts/Dockerfile-testing
Add a Filter for tracing go-restful requests.
Installing the filter into a container,
webservice, or route, will cause the requests
within that scope to be traced, and panics
recovered and reported.
Closes elastic/apm-agent-go#227
> module/apmrestful: add tracing filter

- CHANGELOG.md
- apmtest/httpsuite.go
- module/apmecho/middleware.go
- module/apmecho/middleware_test.go
- module/apmgin/middleware.go
- module/apmgin/middleware_test.go
- module/apmhttp/handler.go
- module/apmhttp/handler_test.go
- module/apmhttp/recovery.go
- module/apmhttprouter/handler.go
- module/apmhttprouter/router_test.go
- module/apmrestful/filter.go
- module/apmrestful/filter_test.go
- scripts/Dockerfile-testing
- transport/transporttest/recorder.go
Introduce a basic HTTP test suite for each of
the web framework instrumentation modules to
run, to test functionality that is expected
to be common across each of them.
For now there are just a few tests for some
edge cases:
- handler does not explicitly write a response
- handler panics before writing a response
- handler panics after writing a response
This uncovered a handful of bugs in the various
web instrumentation modules which have now
been fixed.
We exposed apmhttp.setContext as SetContext,
using it in apmrestful to set context. This allows us
to set the framework for errors originating from
go-restful handlers.
Fixes elastic/apm-agent-go#272
>  module/...: fix panic handling in web instrumentations

- capturebody.go
- context.go
- error.go
- modelwriter.go
- spancontext.go
- utils.go
- validation_test.go
Truncate database statements at 10000 runes, and all other strings at 1024 runes.
> Only permit DB statement to be 10000 runes

- context.go
- docs/configuration.asciidoc
- env.go
- model/marshal.go
- model/marshal_fastjson.go
- model/marshal_test.go
- model/model.go
- modelwriter.go
- module/apmecho/middleware_test.go
- module/apmgin/middleware_test.go
- module/apmgorilla/middleware_test.go
- module/apmhttp/handler_test.go
- module/apmhttprouter/handler_test.go
- module/apmrestful/filter_test.go
- sanitizer.go
- sanitizer_test.go
Record all HTTP request/response headers, with the
exception of "Cookie", which we explode and store
separately.
All headers pass through the field sanitiser. If a
header is included multiple times, we store the
values as an array of strings. Otherwise, we store
just a single string value.
The default value for `ELASTIC_APM_SANITIZE_FIELD_NAMES`
has been updated to include "authorization" and "set-cookie".
Closes elastic/apm-agent-go#277
> Record all HTTP request/response headers

- CHANGELOG.md
- context.go
- docs/api.asciidoc
- example_test.go
- gofuzz.go
- model/maps.go
- model/marshal.go
- model/marshal_fastjson.go
- model/marshal_test.go
- model/model.go
- validation_test.go
Remove the ability to set custom context from
instrumentation modules. It's unclear whether
we will retain this feature, or consolidate on
tags. Until we've made a decision on that, we'll
keep it out of the API for new agents.
Closes elastic/apm-agent-go#282
> apm: remove Context.SetCustom

- context.go
- context_test.go
- model/maps.go
- model/marshal_fastjson.go
- model/marshal_test.go
- model/model.go
- module/apmot/tracer_test.go
- spancontext.go
- spancontext_test.go
Update model.Context.Tags and model.SpanContext.Tags
to use the model.StringMap type, which is a slice of
key/value pairs. Storing tags is now just an append,
with no de-duplication (the server will de-duplicate
when unmarshalling). When resetting transaction and
span objects, we'll now reuse these tags slices.
Closes #283
> Reuse tags memory

- transport/http.go
- transport/http_test.go
Check for 404 responses, adding a hint that APM Server 6.5.0+ is required.
Closes elastic/apm-agent-go#285
> transport: special handling for 404 response

- .travis.yml
- internal/tracecontexttest/Dockerfile
- internal/tracecontexttest/Dockerfile-harness
- internal/tracecontexttest/main.go
- module/apmhttp/handler.go
- module/apmhttp/traceheaders.go
- module/apmhttp/traceheaders_test.go
- scripts/docker-compose-testing.yml
Implement a test service for running the w3c/distributed-tracing test harness, run as a pair of docker-compose services. This showed up a couple of minor issues in our header handling, which are also fixed by this PR.
Closes https://github.com/elastic/apm-agent-go/issues/291
> Implement test service for w3c/distributed-tracing harness

- CHANGELOG.md
- module/apmhttp/client.go
- module/apmhttp/client_test.go
Don't end HTTP client spans as soon as the response
headers have been received, but rather when the
response body has been closed or EOF received.
Closes elastic/apm-agent-go#287
> module/apmhttp: end client span on body closure

- internal/apmschema/schema.go
Need to prefix with '/', to avoid "C:/" being interpreted as a host.
> internal/apmschema: fix file:// URL for Windows

- CHANGELOG.md
- Makefile
- module/apmgrpc/client.go
- module/apmgrpc/client_test.go
- module/apmgrpc/doc.go
- module/apmgrpc/packages.go
- module/apmgrpc/server.go
- module/apmgrpc/server_test.go
- scripts/check_goimports.sh
grpc-go dropped support for versions of Go older than 1.9, so we must do the same.
> module/apmgrpc: only run tests on Go 1.9+

- module/apmhttp/handler_http2_test.go
- module/apmhttp/handler_test.go
http2 no longer builds with Go 1.8, add a build constraint.
> module/apmhttp: don't test http2 with Go 1.8

- internal/tracecontexttest/main.go
Update test service to allow empty Tracestate headers.
See https://github.com/w3c/trace-context/pull/188.
> internal/tracecontexttest: allow empty Tracestate

- docs/api.asciidoc
- example_tracecontext_test.go
- transaction.go
- transaction_test.go
Introduce a new method, Transaction.EnsureParent, which returns
the transaction's parent ID. If the transaction does not have a
parent span recorded, then one is recorded based on the trace ID.
This change is in support of correlation with the RUM agent, for
applications where the initial page load is served by the backend
agent.
Closes elastic/apm-agent-go#298
> Introduce Transaction.EnsureParent

- docs/configuration.asciidoc
- env.go
Reduce ELASTIC_APM_API_BUFFER_SIZE default from 10MB to 1MB. The previous default was excessive. Users can increase it as necessary, which we expect to be uncommon.
> Reduce ELASTIC_APM_API_BUFFER_SIZE default to 1MB

- tracer_test.go
Improve TestTracerRequestSize so that it
yields to the tracer while sending events,
making the timing more predictable.
> apm: improve TestTracerRequestSize

- error.go
- error_test.go
For nil Errors, Error.Send is a no-op.
> apm: add nil check for Error.Send

- module/apmgocql/apmgocql_test.go
TestQueryObserverErrorIntegration has been fixed by
an upstream change to gocql.
> module/apmgocql: remove expected failure

- CHANGELOG.md
- docs/api.asciidoc
- error.go
- gocontext.go
- gocontext_test.go
- modelwriter.go
- module/apmgocql/observer.go
- module/apmhttp/client.go
- module/apmsql/conn.go
- span.go
- tracer.go
- transaction.go
Transaction, Span, and Error are no longer pooled.
Instead, new *Data types are introduced which are
pooled, and those are embedded within their related
top-level object types. We add a read-write mutex
to the Transaction and Span types to guard access
to those such that a concurrent StartSpan and
Transaction.End will not panic.
This change introduces an additional allocation for
each of StartTransaction, StartSpan, and NewError.
The time overhead (measured in nanoseconds) is not
enough to warrant living with the lack of safety.
It is now safe to call End() multiple times, and
to call StartSpan with an ended transaction or parent
span. When StartSpan is called with an ended
transaction, a dropped span will be created.
Closes #317
> Stop pooling top-level objects

- env.go
- env_test.go
- metrics_test.go
- modelwriter.go
- tracer.go
- transport/transporttest/recorder.go
Buffer metrics separately from transactions, spans, and errors, so that the periodically collected metrics do not get evicted by the more frequently reported transactions and spans in a busy system.
Fixes #311
> Buffer metrics separately

- error.go
- modelwriter.go
Tidy up the Error type, moving model.Error out. The model.Error is now built up like the other event types. Bonus: reuse the exception attributes map.
> Remove model.Error field from Error

- internal/sqlscanner/scanner_test.go
- internal/sqlscanner/testdata/tests.json
- internal/sqlscanner/token.go
- internal/sqlutil/signature.go
- internal/sqlutil/signature_test.go
- internal/sqlutil/testdata/tests.json
Move the test cases to JSON docs, so they can be shared with other agents.
Fix a special form of UPDATE where the target table is aliased.
> Move SQL scanning/parsing test cases to JSON

- CHANGELOG.md
- internal/apmhostutil/container.go
- internal/apmhostutil/container_test.go
- internal/apmhostutil/docker_linux.go
- internal/apmhostutil/docker_linux_test.go
- internal/apmhostutil/docker_nonlinux.go
- model/marshal_fastjson.go
- model/model.go
- tracer_test.go
- utils.go
Update the "system" metadata with the container ID, if we detect one. Currently we only support doing this from within Docker containers.
Closes #328
> Add Docker container ID to system metadata

- docs/supported-tech.asciidoc
- module/apmgokit/README.md
- module/apmgokit/doc.go
- module/apmgokit/grpc_test.go
- module/apmgokit/http_test.go
- scripts/Dockerfile-testing
Instrumentation is handled by apmhttp and apmgrpc. This package just has tests and example code.
> module/apmgokit: add tests, examples, docs

- CHANGELOG.md
- docs/api.asciidoc
- model/marshal_fastjson.go
- model/model.go
- modelwriter.go
- module/apmgocql/apmgocql_test.go
- module/apmgrpc/client_test.go
- module/apmhttp/client.go
- module/apmhttp/client_test.go
- module/apmot/example_test.go
- module/apmot/span.go
- module/apmot/tracer_test.go
- module/apmredigo/conn.go
- module/apmredigo/conn_test.go
- module/apmsql/apmsql_go110_test.go
- module/apmsql/apmsql_test.go
- module/apmsql/mysql/mysql_test.go
- module/apmsql/pq/pq_test.go
- span.go
- span_test.go
The type supplied via the StartSpan methods will now be split on dots, and the Type, Subtype, and Action fields populated in order. If the type has only one dot, then action will not be set.
Closes elastic/apm-agent-go#323
> Introduce Span.Subtype, Span.Action

- Jenkinsfile
The new step checkoutElasticDocsTools make the checkout only of the tools to build the docs, it saves about 4G of download.
* The documentation build step goes from 4 min to 1.5 min, so we are about 3 min faster now.
* We added a branch filter for some stages, before those stages only run on master
* We added a parameter to be able running any stage on a PR or branch
> [APM-CI] use new step to download the docs repo

- CHANGELOG.md
- module/apmsql/apmsql_test.go
- module/apmsql/conn.go
database/sql drivers may return driver.ErrBadConn
to indicate that the connection is bad, and should
not be reused. We should not report these errors,
as they are expected by database/sql, and used for
connection pooling/reuse.
Closes #345
> module/apmsql: don't report driver.ErrBadConn

- CHANGELOG.md
- module/apmsql/apmsql_test.go
- module/apmsql/conn.go
Don't report context.Canceled errors from
module/apmsql, they should be expected since
it is only returned due to the caller having
canceled the request.
Closes #347
> module/apmsql: don't report context.Canceled

- module/apmecho/example_test.go
Add an executable example for Middleware, showng that the request context can be passed to apm.StartSpan.
Closes elastic/apm-agent-go#334
> module/apmecho: add code example

- CHANGELOG.md
- docs/api.asciidoc
- error.go
- error_test.go
- modelwriter.go
We introduce a new "Error" field to ErrorLogRecord,
which sets the error's exception data. This can be
used to report error details associated with log
entries, e.g. using logrus's WithError.
For an error created using NewErrorLog, the exception
stacktrace will only ever be populated from the error
value, e.g. by using github.com/pkg/error's StackTrace
method. Calling Error.SetStacktrace will only set the
log's stacktrace. The Culprit will be set from the exception
stacktrace in preference to the log stacktrace.
> apm: support combined exception/log errors

- docs/index.asciidoc
- docs/introduction.asciidoc
Versions go master links to APM Server and APM Overview v6.5 per elastic/apm/issues/19.
> Docs: version documentation links

- module/apmbeego/filter.go
- module/apmbeego/filter_test.go
Add apmbeego.Option and apmbeego.WithTracer, and unexpose the use of apmhttp options. This gives us the flexibility to later move logic into this package if necessary.
> module/apmbeego: add Option & WithTracer

- internal/apmschema/jsonschema/metricsets/common_metricset.json
- internal/apmschema/jsonschema/service.json
- internal/apmschema/jsonschema/spans/common_span.json
- internal/apmschema/jsonschema/spans/v2_span.json
- model/marshal.go
- model/model.go
- module/apmhttp/client.go
- module/apmhttp/client_test.go
- spancontext.go
>  module/apmhttp: add status code to client spans

- .travis.yml
- CHANGELOG.md
- builtin_metrics.go
- metrics_test.go
- version.go
The CPU% metrics should be in the range [0,1], so stop scaling by 100.
Fixes https://github.com/elastic/apm-agent-go/issues/392
> Don't scale CPU metrics

- docs/instrumenting.asciidoc
`apmhttp.Wrap` function receive a `http.Handler` type and in this example was receiving a function. Changing the example to use the `http.HandlerFunc` function which will return a `http.Handler` type.
> fix apmhttp code example when wrapping a function

- CHANGELOG.md
- env_test.go
- tracer.go
- tracer_test.go
- version.go
When Tracer.loop exits, it sets Tracer.active
to false, which races with reads by the method
Tracer.Active. We fix this by changing the
Tracer.active field from a bool to int32, and
using atomic ops.
Fixes #404
> apm: fix data race accessing Tracer.active

- CHANGELOG.md
- builtin_metrics.go
- metrics_test.go
Disable the `agent.*` metrics, as they were ill-defined.
We will reinstate these metrics, or some alternatives,
at a later date after design and discussion with other
agent developers.
Closes elastic/apm-agent-go#396
> Disable agent.* metrics

- CHANGELOG.md
- error.go
- error_test.go
- version.go
github.com/pkg/errors has broken backwards compatibility
on master, which will become 0.9.0. Until we can get rid
of support for the older version (which, undoubtedly, many
people are using), we will support both by using reflection.
Bump version to v1.1.3.
Fixes #408
>  apm: add support for github.com/pkg/errors@master

- CHANGELOG.md
- error.go
- error_test.go
- internal/apmschema/jsonschema/errors/v2_error.json
- model/marshal.go
- model/marshal_fastjson.go
- model/marshal_test.go
- model/model.go
- modelwriter.go
Report whether or not an error occurred within a sampled transaction.
Closes #395
> Add error.transaction.sampled

- CHANGELOG.md
- module/apmot/context.go
- module/apmot/harness_test.go
Bring the code in line with the docs, and do not support follows-from.
Fixes #413
> module/apmot: follows-from is not supported

- docs/configuration.asciidoc
s/tracer/agent/ in ELASTIC_APM_ACTIVE config description,
to make it clearer that the agent is entirely de/activated.
Closes #412
> docs: minor rewording for ELASTIC_APM_ACTIVE

- CHANGELOG.md
- context.go
- docs/configuration.asciidoc
- env.go
- env_test.go
- error.go
- tracer.go
- tracer_test.go
- transaction.go
Introduce the ELASTIC_APM_CAPTURE_HEADERS config,
which controls whether or not HTTP headers will be captured.
Defaults to true.
Closes #390
> Introduce ELASTIC_APM_CAPTURE_HEADERS

- Jenkinsfile
- env_test.go
- tracer_test.go
TestTracerRequestSize now sets a much higher request time,
and allows for greater delays. This will allow for slower
environments while ensuring the request time isn't the
cause for request completion.
TestTracerRequestTimeEnv now just sends a single event,
ensuring the request size is not the cause, and also allows
for greater delays.
Also, update Go to 1.11.4 under Jenkins.
>  Improve test reliability

- CHANGELOG.md
- error.go
- error_test.go
- gocontext.go
Fixes elastic/apm-agent-go#391
Had to change apm.captureError behavior a little bit - instead of returning nil, Error with nil ErrorData is returned. Comments are adjusted.
I think Error.sent() name may be adjusted as there are more cases when ErrorData is nil.
Tests for causer and error interfaces added.
> #391; implement error interface

- model/model.go
Span.Timestamp is the time at which the span started,
not at which the span's transaction started. The code is
correct, just fixing the doc comment.
> model: update Span.Timestamp doc comment

- CHANGELOG.md
- env.go
- metrics.go
- metrics_test.go
- tracer.go
Introduce the config ELASTIC_APM_DISABLE_METRICS,
which disables metrics whose names match any of a list of
wildcard patterns. Currently there is no method to change this
dynamically, but the matching is done in a way to permit this
in the future.
Closes elastic/apm-agent-go#435
> Introduce ELASTIC_APM_DISABLE_METRICS

- Makefile
Fix the for loops in Makefile targets to exit
if any of the iterations fail. This currently
only affects us when modules are enabled, as
otherwise there's just one loop iteration, and
the for loop exits with the last iteration's
result.
> Fix Makefile when running with modules enabled

- CHANGELOG.md
- docs/instrumenting.asciidoc
- module/apmmongo/go.mod
- module/apmmongo/go.sum
- module/apmmongo/monitor.go
- module/apmmongo/monitor_benchmark_test.go
- module/apmmongo/monitor_integration_test.go
- module/apmmongo/monitor_test.go
Bump up the dependency to 1.0.0-rc1, using the new base import path "go.mongodb.org/mongo-driver".
(The apmmongo module is marked experimental because the MongoDB Go Driver has not yet had a stable release, and things may break along the way. Case in point.)
> module/apmmongo: bump 1.0.0-rc1, new import path

- CHANGELOG.md
- error.go
- error_test.go
- error_unix.go
- error_windows.go
- go.mod
- modelwriter.go
- module/apmmongo/monitor.go
- module/apmmongo/monitor_integration_test.go
- module/apmmongo/monitor_test.go
Introduce the ErrorDetailer interface, along with
top-level functions RegisterTypeErrorDetailer and
RegisterErrorDetailer. The former register an
ErrorDetailer with a specific error type, and the
latter registers an ErrorDetailer for all errors.
When an error is created with NewError or NewErrorLog,
we pass the error details through these ErrorDetailers,
giving instrumentation modules and application-specific
code an opportunity to extract details from custom
error types.
In module/apmmongo, we register an ErrorDetailer
that extracts details from mongo.CommandErrors.
Closes #447 
Closes #443
> apm: introduce ErrorDetailer interface

- module/apmhttp/client.go
- module/apmhttp/client_go112_test.go
- module/apmhttp/client_test.go
Add CloseIdleConnections and CancelRequest methods to the RoundTripper type returned by apmhttp.WrapRoundTripper (and internally, WrapClient). These methods simply pass through to the underlying RoundTripper, if it has those methods.
Closes elastic/apm-agent-go#455
> module/apmhttp: CloseIdleConnections and CancelRequest pass through

- CHANGELOG.md
- module/apmhttp/traceheaders.go
- span.go
- span_test.go
- transaction.go
- transaction_test.go
Add TransactionOptions.TransactionID and SpanOptions.SpanID
to enable callers to specify transaction and span IDs. If those fields
are valid/non-zero, they will be used; otherwise random values will
be generated as usual.
Closes #460 
Closes #461
> apm: allow specifying transaction/span ID

- docs/instrumenting.asciidoc
- module/apmelasticsearch/client.go
- module/apmelasticsearch/client_test.go
Capture the request body for more search requests.
Previously we would capture the body only for requests
where the path ended with "/_search". We will now
match the following suffixes:
- "/_search"
- "/_msearch"
- "/_search/template"
- "/_msearch/template"
- "/_rollup_search"
>  module/apmelasticsearch: capture more request bodies

- CHANGELOG.md
- docs/api.asciidoc
- error.go
- gocontext.go
- gocontext_test.go
- modelwriter.go
- span.go
- tracer.go
- transaction.go
- transaction_test.go
Move TraceContext from TransactionData to
Transaction, and SpanData to Span. This
enables an ended transaction or span to
be used as the parent of a span. This is
particularly important to enable
fire-and-forget type patterns, where a
goroutine is spawned that may start a span
after the parent ends.
Transactions, spans, and errors are now
all sent to the tracer goroutine through
a single "chan tracerEvent" channel.
This change incurs a minor (~10%/~50 bytes)
increase in the number of bytes allocated
per transaction. There is no change in number
of allocs, and no significant impact on time
per operation.
Partially addresses #475
> Promote TraceContext to non-pooled types

- CHANGELOG.md
- Makefile
- docs/api.asciidoc
- docs/instrumenting.asciidoc
- gocontext.go
- gocontext_test.go
Introduce apm.DetachedContext, which takes a context.Context
and returns a new context.Context which is effectively a
background context, but with access to the values in the
input context.
DetachedContext can be used to maintain the trace context
required to correlate events, but where the operation is
"fire-and-forget", and should not be affected by the deadline
or cancellation of the input context.
Closes #476
> Introduce DetachedContext function

- gocontext_test.go
Fix a timing related issue in TestDetachedContext,
by ensuring the spans have all been ended by the
time "WithTransaction" returns.
> Fix TestDetachedContext

- .travis.yml
- CHANGELOG.md
Pin go-sql-driver to v1.4.1, which is the last release to support Go 1.8. We'll drop Go 1.8 eventually, but only in a major release.
> Fix go1.8 tests

- module/apmot/context.go
- module/apmot/doc.go
- module/apmot/span.go
- module/apmot/tracer.go
- module/apmot/tracer_test.go
We previously worked around starting spans from
finished/ended transactions by maintaining a
reference to the span context that created the
transaction, and setting its tx property to
nil upon ending it. This was necessary because,
at the time, spans started from ended transactions
would be dropped.
We no longer drop these spans, so we can get rid
of this workaround. Now we just keep a reference
to the transaction within which a span is created,
and always use that.
Closes elastic/apm-agent-go#480
> module/apmot: remove workaround for ended tx

- CHANGELOG.md
- docs/instrumenting.asciidoc
- module/apmbeego/filter.go
- module/apmbeego/filter_test.go
- module/apmchi/middleware.go
- module/apmecho/middleware.go
- module/apmecho/middleware_test.go
- module/apmechov4/middleware.go
- module/apmechov4/middleware_test.go
- module/apmgin/middleware.go
- module/apmgin/middleware_test.go
- module/apmgorilla/middleware.go
- module/apmgorilla/middleware_test.go
- module/apmhttp/requestname.go
- module/apmhttp/requestname_go19.go
- module/apmhttprouter/handler.go
- module/apmhttprouter/router.go
- module/apmhttprouter/router_test.go
- module/apmrestful/filter.go
- module/apmrestful/filter_test.go
Update all HTTP instrumentation modules to group unknown routes. If a route cannot be determined, then the transaction name will be `<METHOD> unknown route`, as in the Node.js agent.
Closes #486
> Update all HTTP instrumentation modules to group unknown routes

- .travis.yml
The default branch is now release-branch.v7, which won't work for Go 1.8. Checkout release-branch.v6 when testing against Go 1.8.
> Use olivere/elastic@release-branch.v6 for Go 1.8

- CHANGELOG.md
- internal/tracecontexttest/Dockerfile
- module/apmmongo/monitor.go
- module/apmmongo/monitor_benchmark_test.go
- module/apmmongo/monitor_integration_test.go
- module/apmmongo/monitor_test.go
At least since 1.0.0, which is what we require, go.mongodb.org/mongo-driver has required Go 1.10. They've just made a code change that breaks Go 1.8, so we need to actually start excluding it now.
> module/apmmongo: set build constraint of go1.10

- module/apmgrpc/ignorer.go
- module/apmgrpc/ignorer_test.go
- module/apmgrpc/server.go
- module/apmgrpc/server_test.go
Add `func WithServerRequestIgnorer(r RequestIgnorerFunc) ServerOption` for ignoring gRPC methods, as described in #530.
> apmgrpc: Add WithServerRequestIgnorer Server Option

- docs/instrumenting.asciidoc
Actual version of module `github.com/elastic/go-sysinfo` seems to have some trouble if I add APM module by only `go get go.elastic.co/apm`
```
$HOME/go/pkg/mod/github.com/elastic/go-sysinfo@v0.0.0-20190103140604-e68552284485/providers/linux/host_linux.go:45:20: cannot convert filepath.Join(hostFS, procfs.DefaultMountPoint) (type string) to type procfs.FS
$HOME/go/pkg/mod/github.com/elastic/go-sysinfo@v0.0.0-20190103140604-e68552284485/providers/linux/host_linux.go:64:42: h.procFS.Path undefined (type procfs.FS has no field or method Path)
$HOME/go/pkg/mod/github.com/elastic/go-sysinfo@v0.0.0-20190103140604-e68552284485/providers/linux/process_linux.go:40:10: s.procFS.Path undefined (type procfs.FS has no field or method Path)
$HOME/go/pkg/mod/github.com/elastic/go-sysinfo@v0.0.0-2019010314 …
```
> Problem on Linux if APM Go agent is installed without -u flag

- CHANGELOG.md
- internal/sqlscanner/scanner.go
- internal/sqlscanner/testdata/tests.json
Ensure we use the rune length everywhere, rather than
assuming single byte runes. This fixes a bug where we
would not properly mark the beginning of the first token
if it starts with a multi-byte rune.
Also, add some comments based on https://github.com/elastic/apm-agent-java/pull/633.
Fixes #535
> internal/sqlscanner: fix for unicode at beginning

- .appveyor.yml
- .travis.yml
- Jenkinsfile
- scripts/jenkins/docker-test.sh
go-pg/pg has some breaking changes which will require
a major version bump (of pg) to v9. For now we'll pin
to v8.0.4, but since we haven't yet released the agent
with apmgopg, it's possible we'll end up setting v9 as
the minimum version.
Fixes #541
> Pin go-pg/pg to v8.0.4

- CHANGELOG.md
- docs/configuration.asciidoc
- env.go
- env_test.go
- testmain_test.go
- tracer.go
- tracer_test.go
- transport/transporttest/recorder.go
Global labels will be added as a metadata.labels field
encoded at the head of each event stream. APM Server 7.2+
will add these to events.
Closes elastic/apm-agent-go#507
> Introduce ELASTIC_APM_GLOBAL_LABELS

- docs/instrumenting.asciidoc
The `go.elastic.co/apm` import statement-, and the 2nd argument to `apm.CaptureError` was missing from the apmhttp module. I added those. Works on my machine :)
> Update missing pieces to the apmhttp module docs

- CHANGELOG.md
- module/apmgorm/apmgorm_test.go
- module/apmgorm/context.go
The RowQuery callback is used when objects are queried with functions like row, rows, count, etc are executed.
Supersedes https://github.com/elastic/apm-agent-go/pull/532.
> Add row_query callback to apmgorm

- Makefile
We stopped vendoring the OT harness a while ago, so there's no need to exclude it from licensing checks any more.
> Makefile: stop excluding apmot/internal/harness

- .appveyor.yml
- .travis.yml
- Jenkinsfile
- module/apmgopg/doc.go
- module/apmgopg/hook.go
- module/apmgopg/hook_test.go
- module/apmgoredis/client.go
- module/apmgoredis/client_test.go
- module/apmgoredis/doc.go
- module/apmgoredis/integration_test.go
Set the minimum Go version requirement to 1.11, so
we can require the use of modules. Trying to support
older versions of Go is going to lead to a worse
experience for the majority.
Since these modules have not yet been in a release of
the agent, this is not considered a breaking change.
Since update the minimum version, pinning go-pg for
Go 1.8-1.10 is no longer necessary. Also, use GOPROXY
to speed up builds and (hopefully) avoid intermittent
package lookup errors.
>  module/{apmgopg,apmgoredis}: require Go 1.11

- .travis.yml
prometheus/procfs reinstated the methods
go-sysinfo relies on, so we can use master
again.
> travis-ci: stop pinning prometheus/procfs

- module/apmelasticsearch/internal/integration/doc.go
- module/apmelasticsearch/internal/integration/olivere_integration_test.go
Require Go 1.10+ for integration tests, as we do for the instrumentation itself.
> module/apmelasticsearch: require go 1.10 for tests

- docs/instrumenting.asciidoc
As `apmhttprouter.New()` wraps httprouter, you don't need to import it. And you also get to avoid `imported and not used: "github.com/julienschmidt/httprouter"` :)
On a side note: httprouter did implement retrieving params from context in [this PR](https://github.com/julienschmidt/httprouter/pull/147) so I don't think you need to wrap a `httprouter.Handler` [here](https://github.com/elastic/apm-agent-go/blob/master/module/apmhttprouter/router.go#L76)
> remove httprouter import from New example

- docs/instrumenting.asciidoc
- docs/supported-tech.asciidoc
- module/apmgopg/hook.go
- module/apmgopg/hook_test.go
Unexpose the QueryHook type, and add the Instrument
function. This hides the implementation details so
that we can potentially support go-pg v9.x.x without
introducing a new package.
> module/apmgopg: unexpose QueryHook, add Instrument

- internal/apmversion/version.go
- transport/http.go
- transport/http_test.go
- version_test.go
The default User-Agent sent by the agent is changed to:
`elasticapm-go/$agent_version go/$go_version`
Closes #527
> transport: update default User-Agent

- module/apmprometheus/gatherer_test.go
In https://github.com/prometheus/client_golang/commit/761a2ff07c763475bff727730e823a8f4d501f36 the DefObjectives var was removed, along with other deprecated bits of the API, in preparation for their v1.0.0 release. We were referencing one deprecated bit in a test: DefObjectives. Replace it with explicit quantile objectives.
> module/apmprometheus: remove refs to DefObjectives

- CHANGELOG.md
- docs/configuration.asciidoc
- env.go
- env_test.go
- error.go
- error_test.go
- internal/pkgerrorsutil/pkgerrors.go
- module/apmzerolog/stack.go
- span.go
- stacktrace/stacktrace.go
- stacktrace/stacktrace_test.go
- tracer.go
- tracer_test.go
- transaction.go
We introduce a new configurable limit for the
number of stack frames to capture, defaulting
to 50.
stacktrace.AppendStacktrace has been improved
for a limit of N > 10, don't allocate space for
N callers up front; that would be wasteful if
there are mostly fewer. Instead, allocate space
for 10 and work our way up, like we do when there
is no specified limit.
Closes elastic/apm-agent-go#526
> Introduce ELASTIC_APM_STACK_TRACE_LIMIT

- CHANGELOG.md
- internal/apmschema/jsonschema/context.json
- internal/apmschema/jsonschema/errors/error.json
- internal/apmschema/jsonschema/metadata.json
- internal/apmschema/jsonschema/request.json
- internal/apmschema/jsonschema/service.json
- internal/apmschema/jsonschema/spans/span.json
- internal/apmschema/jsonschema/stacktrace_frame.json
- internal/apmschema/jsonschema/system.json
- internal/apmschema/jsonschema/user.json
- modelwriter.go
- validation_test.go
Ensure `error.culprit` is truncated at 1024 chars.
Fixes elastic/apm-agent-go#508
> Truncate error.culprit

- internal/apmhostutil/container_linux.go
- internal/apmhostutil/container_linux_test.go
As well as supporting contiguous 64 hex digits, also support truncated UUIDs as used by CloudFoundry Garden.
Closes #576
> apmhostutil: extract CF Garden container IDs

- capturebody.go
- internal/apmhttputil/url.go
- internal/apmstrings/truncate.go
- internal/apmstrings/truncate_test.go
- module/apmhttp/handler_test.go
- utils.go
Ignore request body read errors when capturing the remaining body. Also, limit the amount we read from the body.
Closes elastic/apm-agent-go#568
>  Fix body capture to ignore read errors

- CHANGELOG.md
- apmtest/recordlogger.go
- breakdown.go
- breakdown_test.go
- builtin_metrics.go
- docs/metrics.asciidoc
- env.go
- fnv.go
- fnv_test.go
- internal/apmlog/logger.go
- internal/apmschema/jsonschema/metricsets/metricset.json
- internal/apmschema/jsonschema/span_subtype.json
- internal/apmschema/jsonschema/span_type.json
- internal/apmschema/jsonschema/spans/span.json
- internal/apmschema/jsonschema/transaction_name.json
- internal/apmschema/jsonschema/transaction_type.json
- internal/apmschema/jsonschema/transactions/transaction.json
- internal/apmschema/update.sh
- logger.go
- metrics.go
- model/marshal.go
- model/marshal_fastjson.go
- model/model.go
- modelwriter.go
- span.go
- tracer.go
- transaction.go
- transaction_test.go
- utils.go
Implementation of agent breakdown metrics (https://github.com/elastic/apm/issues/78)
Checklist/TL;DR version of the design:
- On span end:
- On transaction end
- [Reporting metrics](https://docs.google.com/document/d/1-_LuC9zhmva0VvLgtI0KcHuLzNztPHbcM0ZdlcPUl64#heading=h.gkxkryn9w02s)
Closes elastic/apm-agent-go#528
> Breakdown metrics

- apmtest/recorder.go
- env_test.go
- gocontext_test.go
- module/apmchi/middleware_test.go
- module/apmgin/bench_test.go
- module/apmgometrics/gatherer_test.go
- module/apmgorilla/middleware_test.go
- module/apmhttp/handler_bench_test.go
- module/apmlogrus/hook_test.go
- module/apmmongo/monitor_benchmark_test.go
- module/apmot/harness_test.go
- module/apmprometheus/gatherer_test.go
- module/apmsql/apmsql_bench_test.go
- module/apmsql/sqlite3/parser_test.go
- module/apmzap/core_test.go
- module/apmzerolog/writer_test.go
- testmain_test.go
- tracer.go
- tracer_test.go
- transport/transporttest/recorder.go
- validation_test.go
Introduce NewTracerOptions and TracerOptions, providing
a means of specifying the initial tracer configuration
(currently just a limited subset).
We now use NewTracerOptions to start a Tracer with an
initial non-default Transport in all of the tests,
rather than starting with the default and switching
after the fact.
Importing apmtest will now update apm.DefaultTracer to
DiscardTracer, calling the initial value's Close method
first.
We also introduce apmtest.NewRecordingTracer and
deprecate direct use of transporttest.RecorderTransport
in tests. This is in order to encourage tests to use
apmtest, updating the default tracer as described above.
> Provide more control over tracer creation

- env.go
- internal/configutil/duration.go
- internal/configutil/env.go
- internal/configutil/env_test.go
- internal/configutil/list.go
- internal/configutil/size.go
- internal/configutil/wildcards.go
- module/apmhttp/ignorer.go
- tracer.go
- transport/http.go
In preparation for introducing a top-level apmconfig package.
> Move internal/apmconfig to internal/configutil

- CHANGELOG.md
- capturebody.go
- capturebody_test.go
- module/apmecho/middleware.go
- module/apmechov4/middleware.go
- module/apmgin/middleware.go
- module/apmhttp/handler.go
- module/apmhttp/handler_test.go
- module/apmhttprouter/handler.go
- module/apmrestful/filter.go
We optimise apm.BodyCapturer in two ways to reduce its overhead:
- BodyCapturers are now pooled: CaptureHTTPRequestBody will
acquire from the pool, and the new BodyCapturer.Discard method
will release back to the pool.
- We no longer use io.TeeReader to read into a bytes.Buffer,
as that may lead to reading the entire request body into
memory. Since we truncate the captured body anyway, we now
copy only a limited amount into a buffer.
Fixes elastic/apm-agent-go#580
> Optimise BodyCapturer

- CHANGELOG.md
- modelwriter.go
- transaction_test.go
Fix transaction encoding to drop any accumulated
context for non-sampled transactions.
We've been relying on instrumentation to not
set context for non-sampled transactions. If
some instrumentation (e.g. custom code) sets
context, it still shouldn't be sent to the
server for non-sampled transactions.
Closes #583
> Don't send context for non-sampled transactions

- scripts/jenkins/bench.sh
When we changed to using Go modules under Jenkins,
benchmarks stopped being run for modules other than
the top-level module due to how "go test ./..." works.
This change switches the benchmarks to using "make test",
passing flags to "go test" via the GOFLAGS environment
variable.
> scripts/jenkins: fix benchmark script

- CHANGELOG.md
- apmconfig/doc.go
- apmconfig/watcher.go
- apmtest/configwatcher.go
- docs/api.asciidoc
- env.go
- env_test.go
- example_test.go
- tracer.go
- tracer_test.go
- transport/http.go
- transport/http_test.go
We introduce a new package, apmconfig, which
defines a Watcher interface that can be used
for watching for central config changes.
When creating a new Tracer, it will use its
Transport for watching config if it implements
apmconfig.Watcher. The default HTTP transport
implements that interface.
The default behaviour of watching config can
be disabled by setting the new environment
variable ELASTIC_APM_CENTRAL_CONFIG to "false".
For now only the sampler can be updated via
central config. While there is central sampling
config defined, any locally defined Sampler will
be disregarded, whether it be specified via
environment variable or via SetSampler.
Closes elastic/apm-agent-go#512
> Implement central config polling

- breakdown.go
- breakdown_test.go
- docs/configuration.asciidoc
- env.go
- tracer.go
- transaction.go
Add the ELASTIC_APM_BREAKDOWN_METRICS environment
variable, which can be used to disable breakdown metrics.
Closes elastic/apm-agent-go#597
> Introduce `ELASTIC_APM_BREAKDOWN_METRICS` config

- CHANGELOG.md
- apmtest/recorder.go
- apmtest/withtransaction.go
- module/apmgrpc/client.go
- module/apmgrpc/client_test.go
Fix a bug in the client interceptor which would break
trace propagation when facing dropped spans or non-sampled
transactions. In these cases we should propagate the
transaction's trace context, rather than sending nothing
in the outgoing metadata which would restart tracing.
Fixes #601
>  module/apmgrpc: fix trace propagation vs. sampling

- docs/configuration.asciidoc
Add mentions of central config:
- Order of precedence
- ELASTIC_APM_CENTRAL_CONFIG config
Splitting this out of https://github.com/elastic/apm-agent-go/pull/591, so we can land that PR and let it soak a bit while we wait for the server docs to be updated.
> docs: add mentions of central config

- module/apmhttp/client.go
- module/apmhttp/client_test.go
I have not found a way to change the default function "ClientRequestName" in the middleware for HTTP client.
> Added WithClientRequestName function

- transport/http_test.go
If a change isn't consumed before the
timer fires again (which will be nearly
instantaneous, since max-age=0), then
the proceeding request will block waiting
before sending another response, causing
a deadlock in the test.
> transport: fix watcher test again

- module/apmhttp/handler.go
- module/apmhttp/handler_test.go
I added a feature for panic propagation.
More details:
https://github.com/elastic/apm-agent-go/issues/540
https://discuss.elastic.co/t/go-agent-apmhttp-middleware/193927/2
> Added WithPanicPropagation function

- module/apmgoredis/client.go
Our code is using *redis.Client, we need to add a method to return underlaying redis.client after called WithContext()
> added RedisClient() to return underlaying redis.Client

- Jenkinsfile
- https://github.com/elastic/apm-agent-go/pull/614 caused a regression as the env variable is defined at the worker level.
- `@Field` helps to create global variables, therefore `gitBaseCommit` is the new variable which does substitute the environment variable.
- GIT_SHA rather than GIT_BASE_COMMIT as the last one is caused when doing a merge within a PR.
> ci(jenkins): this is required to avoid using a common worker

- docs/instrumenting.asciidoc
Documentation bug fix proper name of the pq driver is "postgres"
> Documentation bug fix

- CHANGELOG.md
- error.go
- error_go113_test.go
- error_test.go
- internal/apmschema/jsonschema/errors/error.json
- internal/apmschema/jsonschema/metricsets/metricset.json
- internal/apmschema/jsonschema/spans/span.json
- internal/apmschema/jsonschema/system.json
- internal/tracecontexttest/main.go
- model/marshal_fastjson.go
- model/model.go
- modelwriter.go
- scripts/before_install.sh
- validation_test.go
We will now report complete error trees in
error.exception: the top-most exception is
the provided error, and any cause/wrapped
error will be reported in an array of causes
to the server.
We will only report at most 50 errors in a tree,
and we break cycles by just ignoring references
to previously seen errors.
The error culprit will now be calculated by
traversing the tree depth-first, returning
the first non-library frame's function name.
This will resolve issues such as #632, where
an error with a complete stack trace is
wrapped by one with only a limited stack trace.
Closes #423
> Report error causes

- CHANGELOG.md
- span.go
- tracer.go
- tracer_test.go
Setting ELASTIC_APM_TRANSACTION_MAX_SPANS=0 now disables all spans. Negative values continue to mean that there are an unlimited number of spans.
Closes #639
> ELASTIC_APM_TRANSACTION_MAX_SPANS=0 disables spans

- CHANGELOG.md
- module/apmzerolog/writer.go
- module/apmzerolog/writer_test.go
Add Writer.MinLevel, which controls the minimum
level of logs to send as errors to Elastic APM.
MinLevel must be >= zerolog.ErrorLevel, otherwise
zerolog.ErrorLevel will be used as the minimum.
Closes #636
> module/apmzerolog: add Writer.MinLevel

- CHANGELOG.md
- context.go
- context_test.go
- docs/api.asciidoc
- docs/instrumenting.asciidoc
- env.go
- example_test.go
- gofuzz.go
- metrics_test.go
- model/marshal_test.go
- model/model.go
- module/apmot/span.go
- module/apmot/tracer_test.go
- spancontext.go
- spancontext_test.go
- transaction_test.go
- utils.go
- validation_test.go
Add Context.SetLabel and SpanContext.SetLabel,
which accept interface{} values. The value may
be a nil, string, bool, or numerical type. Any other
type will be sent as a string using fmt.Sprint.
The SetTag methods remain, but marked as being
deprecated, with a notice that they will be removed
in a future major version.
Closes #572
> Add SetLabel, deprecate SetTag

- CHANGELOG.md
- module/apmhttp/client_test.go
Fix TestClientCancelRequest for Go master.
RoundTripper.CancelRequest is no longer guaranteed
to be called after RoundTrip returns.
> module/apmhttp: fix TestClientCancelRequest

- module/apmgorm/apmgorm_test.go
- module/apmgorm/context.go
There are some cases that gorm can return sql.ErrNoRows when using with postgres and ON CONFLICT DO NOTHING RETURNING *. I think we can safely ignore this error as we're ignoring gorm.ErrRecordNotFound
Also add second argument of redis command trace to understand more clearly about the trace.
> Ignore sql.ErrNoRows

- config_test.go
Fix a race in TestTracerCentralConfigUpdate.
Check for the remote update before unblocking
the server from a second response which would
revert the config.
> Fix TestTracerCentralConfigUpdate race

- transport/http.go
- transport/http_test.go
Clean the server URL path, so we don't trigger redirects due to non-canonical paths at the server.
Fixes #657
> transport: clean server URL path

- context.go
- internal/apmhttputil/remoteaddr.go
- internal/apmhttputil/remoteaddr_test.go
- internal/apmhttputil/url.go
- internal/apmhttputil/url_test.go
- module/apmchi/middleware_test.go
- module/apmgorilla/middleware_test.go
- module/apmhttp/handler_http2_test.go
`context.request.socket.remote_address` should have the direct peer socket (IP) address, not the originating client address. This means we should not parse Forwarded, X-Forwarded-For, etc. in order to determine this field's value. That should instead be left to the server.
Closes #659
> Use direct peer socket address

- docs/configuration.asciidoc
- docs/metrics.asciidoc
- env_test.go
- internal/apmschema/jsonschema/service.json
- model/marshal_fastjson.go
- model/model.go
- utils.go
Adds an optional `ELASTIC_APM_SERVICE_NODE_NAME` config to the agent, along with relevant documentation.
Things to note:
- I ran the `apmschema/update.sh` script, and a lot more things were changed rather than just the expected additions in `service.json`. Is this expected? Should I modify the script to only generate changes in the relevant file?
- I was unable to use `go generate` to generate the `model/marshal_fastjson.go` file (I manually edited the file just so I could get unstuck 😄 ). 
After I pulled the `fastjson` repo and ran the generate command all I kept getting was a strange modules error (I am able to run the tests and everything else just fine):
```console
karen$ go generate
2019/10/13 18:55:45 /Users/karen/go/src/github.com/karencfv/apm-agent-go/model/marshal.go:29:2: could …
```
> Implement ELASTIC_APM_SERVICE_NODE_NAME config

- CHANGELOG.md
- config.go
- profiling.go
- profiling_test.go
- tracer.go
- transport/http.go
- transport/http_test.go
- transport/transporttest/recorder.go
We introduce support for periodically sending
CPU and heap profiles to the APM Server. These
can be enabled by setting the undocumented and
experimental environment variables:
- ELASTIC_APM_CPU_PROFILE_INTERVAL
- ELASTIC_APM_CPU_PROFILE_DURATION
- ELASTIC_APM_HEAP_PROFILE_INTERVAL
This is part of https://github.com/elastic/apm/issues/121
> Introduce experimental profiling support

- internal/apmschema/schema.go
Rather than using go/build to locate the package
to get its directory, just use the source line
info. This is simpler, faster, and works when
the agent is located outside of $GOPATH.
Thanks to @jonbodner for the smarter approach
of using `runtime.Caller`.
Closes #667
> internal/apmschema: fix package dir lookup

- model/generate.sh
Rather than relying on relative location of fastjson
within $GOPATH, use "go run <package>". This means
"go generate" won't work with older versions of Go,
but this is only for agent development so no big deal.
> model: update generate script for modules

- internal/apmhostutil/container_linux.go
- internal/apmhostutil/container_linux_test.go
When k8s is using the systemd cgroup driver,
hyphens in pod UIDs will be escaped and translated
to underscores. We need to reverse this when
parsing the cgroup file.
See https://github.com/elastic/apm/pull/165
> internal/hostutil: unescape systemd cgroup paths

- .ci/jobs/defaults.yml
The pipeline should care only for those branches/tags which are not ^module based
Closes #608
> [apm-ci] branches/tags with the format ^module/ are filtered

- CHANGELOG.md
- config.go
- env_test.go
- internal/tracecontexttest/main.go
- module/apmgrpc/client.go
- module/apmgrpc/client_test.go
- module/apmgrpc/go.sum
- module/apmgrpc/server.go
- module/apmgrpc/server_test.go
- module/apmhttp/client.go
- module/apmhttp/client_test.go
- module/apmhttp/handler.go
- module/apmhttp/handler_test.go
- module/apmhttp/traceheaders.go
- module/apmot/tracer.go
- tracer.go
- transaction.go
We will now look for and propagate the W3C "traceparent" header. We still look for "Elastic-Apm-Traceparent" and use it if present, and otherwise we use the "traceparent" header. We will always send "traceparent" in outgoing requests, and optionally send the "Elastic-Apm-Traceparent" header.
We introduce the `ELASTIC_APM_USE_ELASTIC_TRACEPARENT_HEADER` environment variable, which controls whether or not we send the "Elastic-Apm-Tracparent" header; currently this defaults to true, but we will later flip the value and eventually remove the config altogether. The value is accessed
through the new method, `Transaction.ShouldPropagateLegacyHeader`.
Part of #503 (still need to implement support for "tracestate" to close it)
> Use/send "traceparent" header

- Jenkinsfile
When a new tag, aka a new release, is created then, the automation will kick the opbeans build which consists of the following tasks:
This particular pipeline will push the changes into the `master` branch for the opbeans-go and tag it with the name of the tag version too. Therefore, the opbeans-go pipeline will trigger two builds, the one for its master branch and the other one for the just created tag. This particular flow is implemented within the opbeans-go.
- PRs UI view
- Release tags UI view
A simplistic view
The above build bumped the version to `v1.6.0` and caused to trigger the opbeans-go pipeline
> ci(jenkins): enable opbeans syncup

- CHANGELOG.asciidoc
As discussed on slack, this PR adds a placeholder `CHANGELOG.asciidoc` file to `1.x`. This allows us to merge https://github.com/elastic/docs/pull/1503. During the next release, release notes will overwrite this file and `1.x` release notes will then be published to the documentation!
> [docs] Add placeholder changelog file to 1.x

- scripts/before_install.sh
We were already pinning github.com/go-sql-driver/mysql
for Go 1.8, now we also pin it for 1.9, for which
support has been dropped at head.
> scripts: pin github.com/go-sql-driver for Go <1.10

- internal/apmhttputil/remoteaddr.go
- internal/apmhttputil/remoteaddr_test.go
- internal/apmhttputil/url.go
- internal/apmschema/jsonschema/request.json
- internal/apmschema/jsonschema/spans/span.json
- model/marshal_fastjson.go
- model/model.go
- modelwriter.go
- module/apmelasticsearch/client.go
- module/apmelasticsearch/client_test.go
- module/apmelasticsearch/internal/integration/elastic_integration_test.go
- module/apmelasticsearch/internal/integration/go.mod
- module/apmelasticsearch/internal/integration/go.sum
- module/apmgorm/apmgorm_test.go
- module/apmgorm/context.go
- module/apmhttp/client_test.go
- module/apmot/tracer_test.go
- module/apmsql/conn.go
- module/apmsql/dsn.go
- module/apmsql/mysql/mysql_test.go
- module/apmsql/mysql/parser.go
- module/apmsql/mysql/parser_test.go
- module/apmsql/pq/parser.go
- module/apmsql/pq/parser_test.go
- module/apmsql/pq/pq_test.go
- spancontext.go
- spancontext_test.go
- validation_test.go
Add span.context fields:
- destination.address
- destination.port
- destination.service.type
- destination.service.name
- destination.service.resource
Implement support for (client) HTTP,
Elasticsearch, PostgreSQL and MySQL
(via apmsql or GORM) spans.
> Add span.context.destination.*

- docs/configuration.asciidoc
- module/apmgrpc/client.go
- module/apmgrpc/client_test.go
- module/apmgrpc/go.sum
- module/apmgrpc/server.go
- module/apmgrpc/server_test.go
- module/apmhttp/client.go
- module/apmhttp/client_test.go
- module/apmhttp/go.sum
- module/apmhttp/handler.go
- module/apmhttp/handler_test.go
- module/apmhttp/traceheaders.go
- module/apmhttp/traceheaders_test.go
- module/apmot/go.sum
- module/apmot/tracer.go
- tracecontext.go
- tracecontext_test.go
- transaction.go
Add the field TraceContext.State, which has the new
type TraceState. TraceState is an opaque type, which
internally contains a list of TraceStateEntry objects.
When starting a transaction with StartTransactionOptions,
the TraceContext.State field will only be considered if
both TraceContext.Trace and TraceContext.State are valid.
If this is true, then the state will be stored on the
transaction, and spans created using the transaction.
Server instrumentation in apmhttp, apmgrpc, and apmot
will extract and parse "tracestate" headers, while client
instrumentation will inject "tracestate" headers.
Add missing docs for `ELASTIC_APM_USE_ELASTIC_TRACEPARENT_HEADER`.
Closes #503
Closes #685
> Add "tracestate" propagation

- Makefile
Adds the `--direct_html` flag to the docs build script. See https://github.com/elastic/docs/pull/1642.
> [docs] Add direct_html flag to build script

- internal/tracecontexttest/go.sum
- internal/tracecontexttest/main.go
- module/apmbeego/go.sum
- module/apmchi/go.sum
- module/apmecho/go.sum
- module/apmechov4/go.sum
- module/apmelasticsearch/go.sum
- module/apmelasticsearch/internal/integration/go.sum
- module/apmgin/go.sum
- module/apmgocql/go.sum
- module/apmgokit/go.sum
- module/apmgometrics/go.sum
- module/apmgopg/go.sum
- module/apmgoredis/go.sum
- module/apmgorilla/go.sum
- module/apmgorm/go.sum
- module/apmhttprouter/go.sum
- module/apmlambda/go.sum
- module/apmlogrus/go.sum
- module/apmmongo/go.sum
- module/apmnegroni/go.sum
- module/apmprometheus/go.sum
- module/apmredigo/go.sum
- module/apmrestful/go.sum
- module/apmsql/go.sum
- module/apmzap/go.sum
- module/apmzerolog/go.sum
- scripts/genmod/go.sum
Update tracecontexttest, which runs tests from
https://github.com/w3c/trace-context against the
agent, to remove the special handling of tracestate
headers and instead rely on the support recently
added to the agent code.
> tracecontexttest: remove tracestate special case

- .ci/jobs/defaults.yml
- Jenkinsfile
Adds reference repos.
These correspond to repos and download locations which can be seen in [the Jenkins job which mirrors them](https://apm-ci.elastic.co/job/jenkins-git-fetch-reference/).
> Add reference repo for apm-agent-go

- Jenkinsfile
- scripts/jenkins/windows/install-tools.bat
- scripts/jenkins/windows/uninstall-tools.bat
This reverts commit 4b3f3047ac8ca73fce1ac35424106c4a64e84b85.
Caused by https://github.com/chocolatey/chocolatey.org/issues/804
The revert does only care for the latest version, it does not revert the unrequired changes with the CI ephemeral workers (delete workspace and uninstall the go version)
> Revert "ci(jenkins): Install latest golang version for Windows (#702)"

- Jenkinsfile
Fixes the current issue when running the opbeans release with the pipeline. 
Further details [here](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-go%2Fapm-agent-go-mbp/detail/v1.7.0/2/pipeline#step-397-log-8)
See [JENKINS-41929](https://issues.jenkins-ci.org/browse/JENKINS-41929)
> ci(jenkins): fixes known issue with params/env variables

- Jenkinsfile
```
[2020-02-26T12:33:51.150Z] + cd /var/lib/jenkins/workspace/agent-go_apm-agent-go-mbp_master/src/github.com/labstack
[2020-02-26T12:33:51.150Z] + git clone https://github.com/labstack/echo
[2020-02-26T12:33:51.150Z] Cloning into 'echo'...
[2020-02-26T12:34:23.223Z] fatal: unable to access 'https://github.com/labstack/echo/': Failed to connect to github.com port 443: Connection timed out
```
here - [step](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-go%2Fapm-agent-go-mbp/detail/master/120/pipeline/86#step-140-log-128)
Caused by https://issuetracker.google.com/issues/146072599
> ci(jenkins): retry/sleep to avoid timeout issues with GitHub

- CHANGELOG.asciidoc
- breakdown.go
- breakdown_internal_test.go
Add struct padding for 32-bit architectures, for 64-bit fields being used in atomic.AddInt64.
Fixes #727
> Fix breakdown metrics on 32-bit architectures

- docs/introduction.asciidoc
This PR adds a link to the Agent/Server compatibility matrix.
For https://github.com/elastic/apm/issues/229.
> docs: Add link to Agent/Server compatibility

- Jenkinsfile
- scripts/jenkins/build-test.sh
- scripts/jenkins/build.sh
- scripts/jenkins/test.sh
Split build-test.sh into two different scripts to retry if there are build errors when fetching the dependencies from github, see the below error:
```
[2020-03-27T14:35:15.622Z] Cloning into '/var/lib/jenkins/workspace/agent-go_apm-agent-go-mbp_master/src/github.com/prometheus/procfs'...
[2020-03-27T14:35:15.622Z] fatal: unable to access 'https://github.com/prometheus/procfs/': Failed to connect to github.com port 443: Connection timed out
[2020-03-27T14:35:15.622Z] package github.com/prometheus/procfs: exit status 128
```
Timeout issues are still a problem in the GCP, for such, we do use the retry/sleep approach. On the other hand, by decoupling the script in two different steps will help to retry the test step when there are genuine test failures, aka faster feedback.
> ci(jenkins): add resilience when timeout issues

- CHANGELOG.asciidoc
- config.go
- config_test.go
- docs/configuration.asciidoc
- env_test.go
- error.go
- error_test.go
- metrics_test.go
- module/apmecho/middleware.go
- module/apmechov4/middleware.go
- module/apmgin/middleware.go
- module/apmgrpc/server.go
- module/apmhttp/handler.go
- module/apmhttprouter/handler.go
- module/apmlogrus/hook.go
- module/apmrestful/filter.go
- module/apmzap/core.go
- module/apmzerolog/writer.go
- profiling.go
- tracer.go
- transaction.go
- transaction_test.go
We introduce the ELASTIC_APM_RECORDING configuration.
This is a boolean configuration that defaults to true,
controlling whether events are recorded and sent. When
recording is true there should be no change; when false:
- Transactions will always be recorded as "unsampled",
and will be silently discarded when ended, without
affecting tracer statistics
- Spans will all be dropped by virtue of transactions
all being unsampled
- Captured errors will not have details filled in, and
will be silently discarded when "sent" without affecting
tracer statistics
- Breakdown metrics will not be updated
- Metrics gathering will be disabled
Recording can be updated via central config and by using
the new Tracer.SetRecording method.
We also introduce a new Tracer.Recording method which
reports whether …
> Introduce "recording" config

- internal/ringbuffer/buffer_test.go
This fixes a dropped error variable in `internal/ringbuffer`.
> internal/ringbuffer: Fix Dropped Test Error

- CHANGELOG.asciidoc
- module/apmelasticsearch/client.go
The apmelasticsearch `roundTripper` did not implement `CloseIdleConnections` and we (@charith-elastic who did the investigation) believe we observed a goroutine leak as a consequence of that. 
This PR adds support for `CloseIdleConnections` and propagates it to the wrapped transport/ `RoundTripper` if it implements it.
> Implement CloseIdleConnections on apmelasticsearch

- model/marshal.go
- model/marshal_test.go
`url.full` is not set when path is empty but is when rootless.  This makes a difference in the APM UI:
> set url.full even when path is empty

- docs/api.asciidoc
Supersedes https://github.com/elastic/apm-agent-go/pull/755
> docs: fix typo

- CHANGELOG.asciidoc
- module/apmot/tracer.go
- module/apmot/tracer_test.go
- tracer.go
If the SpanContext passed to Inject does not contain a Transaction, then Inject would panic due to a nil pointer dereference. Transaction will always be nil in the result of Extract, and will only be set when creating a new span with the context.
We were using the transaction to check if we should inject the legacy header. Since this is not a dynamic configuration setting, we can just use the tracer instead, by adding a `tracer.ShouldPropagateLegacyHeader` method.
Fixes #761 
Supersedes #762
> module/apmot: fix nil-pointer deref in Inject

- tracer.go
Clarify that DefaultTracer should typically be closed when calling NewTracer/NewTracerOptions.
See https://github.com/elastic/apm-agent-go/issues/770
> Add note about DefaultTracer in NewTracer[Options]

- transport/transporttest/recorder.go
This is an API change, but the test packages are not considered stable. Not bumping a major version for this.
> transport/transporttest: decode Labels as IfaceMap

- Jenkinsfile
It separates the before_install and build scripts into two different retries on CI
With previous approach, if the second step (build) failed, then the before_install will be executed again, even if it already executed with success
> chore(ci): separate retries into two separate steps

- Jenkinsfile
- scripts/jenkins/build-test.sh
It splits the execution of the build & test scripts for OSX, following same strategy used in the Linux workers
Consistency
- Closes #797
> chore(ci): use same approach for *nix workers

- tracecontext_test.go
Go 1.15 doesn't care for `string(0)`, prefers `string(rune(0))`.
> Fix string(0) in test for Go 1.15

- docs/instrumenting.asciidoc
- docs/supported-tech.asciidoc
This PR fixes two external 404s in the Go agent documentation.
> docs: fix gin 404s

- module/apmhttp/clienttrace.go
To align with existing HTTP spans.  Compare and old and new breakdowns in the UI as a result:
> group httptrace spans as external.http

- config.go
- model/marshal_fastjson.go
- model/model.go
- modelwriter.go
- module/apmgrpc/client_test.go
- module/apmot/harness_test.go
- sampler.go
- sampler_test.go
- span_test.go
- tracecontext.go
- tracecontext_test.go
- tracer.go
- transaction.go
- transaction_test.go
- utils_go10.go
- utils_go9.go
Introduce the new ExtendedSampler interface, which
Samplers may implement to return the effective
sampling rate. This is implemented by the built-in
ratioSampler.
When starting a root transaction we now call the
ExtendedSampler method if implemented, and store
the effective sampling rate in the transaction's
tracestate under our "es" vendor key.
When receiving tracestate, we parse our "es" vendor
value and extract the sample rate.
When encoding transactions and spans we record the
sample rate (from tracestate) in the transaction and
span events.
> Record {transaction,sample}.sample_rate

- apmtest/recorder_test.go
- model/marshal_fastjson.go
- model/marshal_test.go
- model/model.go
- scripts/jenkins/windows/build-test.bat
- transport/transporttest/recorder.go
This is part of https://github.com/elastic/apm-agent-go/issues/786. No metadata collection yet, just adding the types and a method to RecorderTracer for testing.
This unblocks translating [OpenTelemetry cloud semantic conventions](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/resource/semantic_conventions/cloud.md) while we continue to work on collecting metadata in the agent.
> model: add Cloud metadata types

- CHANGELOG.asciidoc
- internal/apmhostutil/container_linux.go
- internal/apmhostutil/container_linux_test.go
Relax the regular expression to match additional paths like:
- 12:pids:/kubepods/kubepods/besteffort/pod0e886e9a-3879-45f9-b44d-86ef9df03224/244a65edefdffe31685c42317c9054e71dc1193048cf9459e2a4dd35cbc1dba4
- 10:cpuset:/kubepods/pod5eadac96-ab58-11ea-b82b-0242ac110009/7fe41c8a2d1da09420117894f11dd91f6c3a44dfeb7d125dc594bd53468861df
Closes #783
> internal/apmhostutil: relax k8s cgroup regex

- apmtest/env.go
- config.go
- docs/configuration.asciidoc
- internal/apmcloudutil/aws.go
- internal/apmcloudutil/aws_test.go
- internal/apmcloudutil/azure.go
- internal/apmcloudutil/azure_test.go
- internal/apmcloudutil/gcp.go
- internal/apmcloudutil/gcp_test.go
- internal/apmcloudutil/provider.go
- internal/apmcloudutil/provider_test.go
- tracer.go
- tracer_test.go
- utils.go
Add support for fetching cloud metadata for AWS, Azure, and GCP.
Based on the Python reference implementation: https://github.com/elastic/apm-agent-python/pull/826
By default we attempt to sniff metadata for all cloud providers. This
can be overridden by setting the environment variable
`ELASTIC_APM_CLOUD_PROVIDER` to one of:
"none", "aws", "azure", or "gcp".
We set a short (100ms) socket connect timeout, and a slightly longer
overall timeout (1s) for fetching the cloud metadata.
In tests we disable cloud metadata fetching by default. There are
currently no functional tests, as that would rely on us running in a
known cloud environment.
The PR has been manually tested in Google Compute Engine and
Google Cloud Run. Otherwise we're relying on the test data from
the Python agent.
Closes #786
> Collect cloud metadata

- CHANGELOG.asciidoc
- module/apmhttp/handler.go
- module/apmhttp/handler_test.go
- scripts/before_install.sh
If the http.ResponseWriter implements io.ReaderFrom,
make sure the wrapped ResponseWriter also does and
passes through.
Closes #826
> module/apmhttp: implement io.ReaderFrom in wrapper

- sampler.go
- scripts/before_install.sh
- span_test.go
- tracecontext.go
- transaction.go
- transaction_test.go
We already had sampling rate rounding, but it
was using the older proposal of 3 decimal places,
and did not clamp the lower bound.
Updated to use the same logic in both the ratio
sampler implementation, and the sampler
implementation independent interpretation of the
sample rate.
Note that we intentionally round in two places:
once in the sampler implementation for the
initial sampling decision, and once in the code
that injects the rate into trace context to guarantee
an upper bound for tracestate.
Also, use the "round" function instead
of math.Round directly, to support older
versions of Go.
> Update sample rate precision handling

- CHANGELOG.asciidoc
- transaction.go
- transaction_test.go
Fix Transaction.Discard so that it sets TransactionData
to nil, like its documentation says. This is necessary
to avoid adding a transaction to the `sync.Pool` multiple
times (e.g. by calling End after after it has been discarded.)
Closes #835
> Transaction.Discard sets TransactionData to nil

- docs/log-correlation.asciidoc
This PR fixes a documentation link that will break when `7.10` becomes the `current` stack version. It conditionally changes the link location of the Logs app docs based on the stack version defined in github.com/elastic/docs ([here](https://github.com/elastic/docs/blob/master/shared/versions/stack/current.asciidoc)).
```asciidoc
ifeval::["{branch}"=="7.9"]
APM to the {apm-app-ref}/xpack-logs.html[Logs app].
endif::[]
ifeval::["{branch}"!="7.9"]
APM to the {observability-guide}/monitor-logs.html[Logs app].
endif::[]
```
Admittedly, this isn't pretty, but it's the cleanest way to ensure this link continues to work for users who click it before and after the `7.10` release.
Tested by building locally with `:branch:` overridden to `7.9`, `7.10`, and `master`.
**This PR will need to be …
> docs: add ifeval for 7.10 release

- docs/log-correlation.asciidoc
Cherry-picks the following commit to `1.x`:
* docs: add ifeval for 7.10 release #839
> [1.x] docs: add ifeval for 7.10 release #839

- CONTRIBUTING.md
Add missing steps to release procedure. These are necessary for the elastic.co docs to be updated for the relevant major release branch.
> CONTRIBUTING: add steps about updating branch

- CHANGELOG.asciidoc
- module/apmsql/apmsql_test.go
- module/apmsql/driver.go
Fixes https://github.com/elastic/apm-agent-go/issues/848
> module/apmsql: add tracingDriver.Unwrap method

- module/apmot/context.go
- module/apmot/harness_test.go
- module/apmot/tracer.go
This pull request is a candidate for solving issue https://github.com/elastic/apm-agent-go/issues/843
> Allow overriding the span ref validation

- docs/log-correlation.asciidoc
This PR cleans up the conditional code added in https://github.com/elastic/apm-agent-go/pull/839 for the `7.10` stack release.
> docs: clean up conditional code

- docs/configuration.asciidoc
Missing the crucial word "not".
> docs: fix typo in ELASTIC_APM_RECORDING config

- CHANGELOG.asciidoc
- config.go
- config_test.go
- modelwriter.go
- tracer.go
- transaction.go
Closes https://github.com/elastic/apm-agent-go/issues/821
> Make sanitize_field_names centrally configurable

- config_test.go
- env_test.go
- tracer_test.go
- transport/http.go
- transport/http_test.go
The Go Agent will continue to support SERVER_URLS,
but we will de-epmphasise its use in favour of using
load balancer proxies with agents generally. We never
actually documented SERVER_URLS in the user docs,
so nothing to do there.
Closes #850
> Update tests and doc comments to use SERVER_URL

- config.go
- config_test.go
- internal/apmcloudutil/provider.go
- internal/apmcloudutil/provider_test.go
- internal/apmlog/logger.go
- internal/apmlog/logger_test.go
- tracer.go
- utils.go
`$ELASTIC_APM_LOG_LEVEL` now defines the local value, and this can be overridden via central config. If central config is updated and then removed, we'll revert back to the local value like with other config.
If a custom logger is defined, or no log file is specified, the `log_level` attribute is ignored regardless of whether central config is used. If a custom logger is defined we will log a warning to it about the central config change being ineffective.
Closes #829
> Make `log_level` centrally configurable

- internal/apmlog/logger.go
- Add the "trace" level.
- In addition to "warn", we should also accept "warning".
See the spec: https://github.com/elastic/apm/blob/master/specs/agents/logging.md
(Thanks @trentm!)
> internal/apmlog: fix log levels

- model/marshal_fastjson.go
- model/model.go
This will be used by the OpenTelemetry exporter.
We should probably be using this for named type
methods in the Go Agent too, but that can come
later.
> model: add "classname" to stacktrace frames

- CHANGELOG.asciidoc
- module/apmgrpc/client.go
- module/apmgrpc/client_test.go
Update the apmgrpc client interceptor to record
span destination address/port and context for
service maps.
Closes https://github.com/elastic/apm-agent-go/issues/767
> module/apmgrpc: set span destination context

- context.go
- error.go
- modelwriter.go
- sanitizer_test.go
- transaction.go
Some light refactoring to move "context" model building
logic out of modelwriter and into the Context.build method.
There remains some context model building in modelwriter
(related to setting destination service type) because it
requires additional information outside of "context", i.e.
the span type.
> Tidy up modelwriter

- scripts/before_install.sh
Recent versions of go-chi break compatibility with older versions of Go.
> Pin go-chi to v1.5.1 for older versions of Go

- docs/configuration.asciidoc
It moves `ELASTIC_APM_API_KEY` from `H4` to `H3`, so that it appears in the right menu.
While looking up the docs, I found this variable is not in the right pane menu, which was weird. Please see https://github.com/elastic/docs/blob/799be2ba9c4cdd926ade46964c18b61b7b16cc80/resources/web/docs_js/index.js#L34, where only H1, H2 and H3 are candidates to be items in the right panel.
Please discard this PR if this variable is a child element of `ELASTIC_APM_SECRET_TOKEN`.
> docs: make API_KEY variable to appear in the right menu

- scripts/docker-test.sh
- scripts/jenkins/before_install.sh
- scripts/jenkins/bench.sh
- scripts/jenkins/build.sh
- scripts/jenkins/docker-test.sh
- scripts/jenkins/jenkins.go.mod
- scripts/jenkins/jenkins.go.sum
- scripts/jenkins/setenv.sh
- scripts/jenkins/test.sh
- scripts/moduledirs.sh
In 1.16, by default go will complain if go.mod
is missing dependencies. In CI this is occurring
due to the installation of tools that are not
present in the top-level go.mod.
To avoid adding dependencies for agent consumers,
introduce a go.mod specifically for installing
tools used only in CI.
> scripts/jenkins: fix CI builds on 1.16

- scripts/before_install.sh
Fix the build. prometheus/client_golang@master no longer works with older versions of Go, due to use of runtime/debug.ReadBuildInfo:
https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-go%2Fapm-agent-go-mbp/detail/PR-914/1/pipeline
> [2021-03-15T01:45:02.535Z] # github.com/prometheus/client_golang/prometheus
> [2021-03-15T01:45:02.535Z] ../../github.com/prometheus/client_golang/prometheus/go_collector.go:388:15: undefined: debug.ReadBuildInfo
> Pin pre-module versions of Go to older Prometheus

- capturebody.go
Add a RWMutex to BodyCapturer so that it can be used concurrently, e.g. while recording errors.
Related to https://github.com/elastic/apm-agent-go/pull/906
> Make BodyCapturer safe for concurrent access

- CHANGELOG.asciidoc
- docs/instrumenting.asciidoc
- docs/supported-tech.asciidoc
- module/apmawssdkgo/session.go
- module/apmawssdkgo/sqs.go
- module/apmawssdkgo/sqs_test.go
Add instrumentation for SQS methods for sending/receiving/deleting messages.
Note: 
Ignoring message queues is part of the [messaging spec](https://github.com/elastic/apm/blob/master/specs/agents/tracing-instrumentation-messaging.md#ignore_message_queues-configuration), but will be included later. This is being tracked in https://github.com/elastic/apm-agent-go/issues/934.
closes https://github.com/elastic/apm-agent-go/issues/883
> Instrument RPC calls to amazon SQS

- model/marshal_fastjson.go
- model/model.go
- module/apmawssdkgo/sns.go
- module/apmawssdkgo/sns_test.go
- module/apmawssdkgo/sqs.go
- module/apmawssdkgo/sqs_test.go
- spancontext.go
Looping back to this, since it was a TODO from when first implementing `sqs` instrumentation.
> Add context message queue name

- capturebody.go
Fixes a nil pointer exception on the benchmark `BenchmarkBodyCapturer`.
The `Context.request` field wasn't set in the benchmark and is being
passed in the `BodyCapturer.setContext()` call as nil, causing an NPE
when `req.PostForm` is accessed.
The bug seems to have been introduced in #906.
This might not be the right fix since I'm not very familiar with the
codebase.
Closes #952
> BodyCapturer: Fix NPE on benchmark when nil Context.request

- CHANGELOG.asciidoc
- module/apmot/span.go
- module/apmot/tracer_test.go
Handles the `http.host` tag and treats it as the `url.Host` value when
the `url.Host` hasn't been set and that OpenTelemetry tag is set to a
value.
Closes #917
> apmot: Handle `http.host` tag as `url.Host`

- Makefile
- go.mod
- go.sum
- scripts/before_install.sh
- tools.go
This PR adds a check for vanity imports to be updated on CI.
Ping @axw
Closes #844
> chore: fixes vanity import.

- internal/apmschema/jsonschema/metricset.json
APM agent json schema automatic sync
*Changeset*
* https://github.com/elastic/apm-server/commit/07444287f Add support for histograms to metrics intake (https://github.com/elastic/apm-server/pull/5360)
> synchronize schema spec

- module/apmrestfulv3/filter.go
- module/apmrestfulv3/filter_example_test.go
- module/apmrestfulv3/filter_test.go
- module/apmrestfulv3/route.go
- module/apmrestfulv3/route_test.go
I think I made a mistake from my  [previous PR](https://github.com/elastic/apm-agent-go/pull/968). The build tag supposed to be `go1.11` instead I set it to `go1.14`, that why [this issue](https://github.com/elastic/apm-agent-go/issues/969) #969  happen where the code won't compile on go1.13
> fix: change build tags for apmrestfulv3 to go1.11

- CHANGELOG.asciidoc
- context.go
- context_test.go
If Context.SetUsername is called explicitly, don't automatically set the username based on HTTP user info (which may or may not exist.)
Fixes https://github.com/elastic/apm-agent-go/issues/970
> Context.SetUsername takes precedence

- CHANGELOG.asciidoc
- module/apmhttp/clienttrace.go
If TLSHandshakeTimeout is something extremely low, like 1ns,
then it can happen that TLSHandshakeDone is called without
TLSHandshakeStart having been called. Check the TLS span is
non-nil before ending it.
Closes https://github.com/elastic/apm-agent-go/issues/981
> module/apmhttp: fix panic in WithClientTrace

- CHANGELOG.asciidoc
- module/apmhttp/clienttrace.go
- span.go
Fix a deadlock that can occur when concurrently ending a parent and child span, due to the parent waiting for the child to release the transaction lock, and the child waiting to lock the parent. Locks are now taken in a consistent order.
Add synchronisation to the httptrace handlers implemented by the `module/apmhttp.WithClientTrace` option. Sayeth the httptrace docs:
> Functions may be called concurrently from different goroutines and
some may be called after the request has completed or failed.
There's a minor enhancement to the handlers to set the Connect span outcome to "failure" if an error occurred.
Fixes https://github.com/elastic/apm-agent-go/issues/994
> Concurrency fixes

- module/apmelasticsearch/client.go
- module/apmelasticsearch/client_test.go
- module/apmhttp/client.go
Send the traceparent header to elasticsearch, now that ES parses it from incoming requests.
Closes https://github.com/elastic/apm-agent-go/issues/987
> send traceparent header to ES

- module/apmawssdkgo/session.go
- module/apmawssdkgo/session_test.go
A noop guard was missing in the `complete()` fn.
Add the guard and verify we are not panicking when
closing different spans.
closes #1005
> [apmawssdkgo] don't panic on unsupported services

- module/apmfasthttp/server_test.go
the transaction is ended after the response body
is fully written, so a single call to
`tracer.Flush()` may not have an event yet
enqueued.
before this change, I was able to get the test to reliably panic with `go test . -count=10000 -failfast`. over several runs on my local machine after this change, I have not gotten the panic.
> re-flush until transaction has been closed

- internal/testdata/json-specs/span_types.json
APM agent specs automatic sync
*Changeset*
* https://github.com/elastic/apm/commit/10b6514 add application handler (https://github.com/elastic/apm/pull/503)
> test: synchronizing json spec

- scripts/tagversion.sh
Adds a conditional on `scripts/tagversion.sh` which uses `gsed` as the
`sed` binary. Last, it uses `bash` instead of `sh` since the `echo -n`
wasn't properly working on that shell for macOS.
> scripts: Fixup `tagversion.sh` for Darwin

- CHANGELOG.asciidoc
- context.go
- gofuzz.go
- model/marshal_fastjson.go
- model/marshal_test.go
- model/model.go
- module/apmfiber/middleware_test.go
- module/apmgrpc/server_test.go
- module/apmhttp/handler_http2_test.go
Deprecates the `http.request.socket.encrypted` field in the apm agent,
and stops recording it in the modules that populated that field:
- `module/apmhttp`
- `module/apmgrpc`
- `module/apmfiber`
Closes elastic/apm-agent-go#1122
> Stop recording `http.request.socket.encrypted`

- module/apmgoredisv8/hook.go
- module/apmgoredisv8/hook_test.go
Add span destination for redisv8 hook to support elastic apm services map.
> add span destination

- module/apmgrpc/go.sum
- module/apmgrpc/server.go
- module/apmgrpc/server_test.go
This allows the handler to retrieve the transaction from it's context, to e.g. create spans.
This closes #1148
> feat(apmgrpc): wrap the server-stream with transaction-ctx

- CHANGELOG.asciidoc
- utils.go
If logging isn't configured, `apmlog.DefaultLogger` will be nil. `apmlog.DefaultLogger` has a pointer-to-struct type, so converting it to apmcloudutil.Logger results in a non-nil interface value with a nil pointer value.
> Fix apmcloudutil logger assignment

- CHANGELOG.asciidoc
- sanitizer.go
Don't update the header values slice, replace it. See https://github.com/elastic/apm-agent-go/pull/1156#issuecomment-978751558
Replaces https://github.com/elastic/apm-agent-go/pull/1156
> Fix data race in HTTP request header sanitisation

- CHANGELOG.asciidoc
- error.go
- internal/apmgodog/suitecontext_test.go
- span.go
- span_test.go
- transaction.go
- transaction_test.go
Apart from HTTP and gRPC, which set outcome based on the status code, set the default outcome to "success" by default, or "failure" if any errors were captured within the transaction or span.
This brings us into line with the agent spec for transaction and span outcome:
- https://github.com/elastic/apm/blob/master/specs/agents/tracing-transactions.md#transaction-outcome
- https://github.com/elastic/apm/blob/master/specs/agents/tracing-spans.md#span-outcome
> For other protocols, we can default to the following behavior:
>
> - failure when an error is reported
> - success otherwise
> Set default outcome according to spec

- Jenkinsfile
The original timeout was set three years ago. Since that time, test times have gradually been moving up:
This isn't necessarily due to changes in the time the tests take. Instead, the time it takes to provision workers and prepare them can vary considerably.
Therefore, I'm increasing the timeout for tests from 1 hour to 2 hours just to prevent the recent failures that we've seen where timeouts have been exceeded, causing the test suite not to report a result.
> Increase test pipeline timeout

- error.go
- error_test.go
- model/marshal_fastjson.go
- model/model.go
- modelwriter.go
- scripts/before_install.sh
Adds a new `transaction.name` field which is recorded when a transaction
is set for the error.
Closes #1154
> error: Record `transaction.name` when available

- module/apmgocql/apmgocql_test.go
- module/apmgocql/observer.go
Currently there is a possibility to receive a panic, while using apmgocql module, this situation can occur while passing context which does not have apm transaction attached
> fix: panic on gocql

- Jenkinsfile
- scripts/before_install.sh
- tracecontext.go
- tracecontext_test.go
Use apm-integration-testing 7.x branch for testing apm-agent-go v1.
We'll update apm-integration-testing's main branch to test v2.
See https://github.com/elastic/apm-agent-go/issues/1184
> CI: use apm-integration-testing/7.x for v1

- module/apmfiber/middleware.go
removed fasthttp import from apmfiber because all fasthttp status codes were copied from net/http package.
> remove unnecessary fasthttp import from apmfiber module

- span.go
- span_test.go
cases:
0: never capture stacktraces
-1: always capture stacktraces
Closes https://github.com/elastic/apm-agent-go/issues/465
> handle special cases for span frames min duration

- CHANGELOG.asciidoc
- config.go
- config_test.go
- env_test.go
- features/api_key.feature
- features/azure_app_service_metadata.feature
- features/outcome.feature
- features/user_agent.feature
- internal/apmgodog/suitecontext_test.go
- module/apmgin/bench_test.go
- module/apmhttp/handler_bench_test.go
- module/apmsql/apmsql_bench_test.go
- tracer_test.go
- transport/http.go
- transport/http_test.go
Update User-Agent to match the [agent spec](https://github.com/elastic/apm/blob/main/specs/agents/transport.md#user-agent), including service name and service version if it is specified. User-Agent no longer includes the Go runtime version, but this is still available in `service.runtime.version`.
The `transport.NewHTTPTransportOptions` function is removed, and `transport.NewHTTPTransport` is updated to take HTTPTransportOptions instead now that we can break the API. Use env vars as defaults only if values are not specified in the options struct, aligning with behaviour of `apm.NewTracerOptions`.
Update to the latest shared agents Gherkin spec.
Closes https://github.com/elastic/apm-agent-go/issues/1136
> Include service name and version in User-Agent

- docs/api.asciidoc
- docs/configuration.asciidoc
- docs/introduction.asciidoc
- docs/upgrading.asciidoc
Links updated as per elastic/observability-docs#1385. The old links will break when 7.17 releases. This PR and all backports must be merged before the 7.17 release. Thanks!
> Doc links update

- docs/api.asciidoc
- docs/configuration.asciidoc
- docs/introduction.asciidoc
- docs/upgrading.asciidoc
Backports https://github.com/elastic/apm-agent-go/pull/1199 to 1.x
> [1.x] Fix doc links

- CHANGELOG.asciidoc
- apmtest/testlogger.go
- config.go
- logger.go
- tracer.go
Since we're making breaking changes, add the Warningf method directly to Logger and remove WarningLogger.
> Fold WarningLogger info Logger

- CHANGELOG.asciidoc
- config_test.go
- tracer.go
- tracer_test.go
- transport/http.go
- transport/http_test.go
- transport/transporttest/recorder.go
Extends the HTTP Transport with a new method that queries the remote APM
Server `/` endpoint to obtain its version. Allowing the tracer to drop
unsampled transactions when the APM Server is version `8.0.0` or higher.
The version will be cached in a local variable until the APM Server URL
changes which will refresh the APM Server's version. The tracer launches
a goroutine to update the version when it is instantiated and refreshes
the remote server version every 10 seconds.
Any SendStream errors will cause the version cache to be invalidated and
will be refreshed the next time the ticker runs. It may cause unsampled
to be sent to the APM Server while the cache is invalid.
Closes #1153
> tracer: Drop unsampled txs when APM Server >= 8.0

- Jenkinsfile
Fixes an issue with the `master` stage since a return closure within another return closure doesn't work
Simplify the try/finally and avoid to use the artificial error step, there is no need
> ci: go master version stage is not triggered

- transport/http_test.go
This test fails very rarely on my machine, but occasionally in CI. It can apparently happen that the (200 OK) response from the server is received by the client, despite the context having been cancelled. Make sure the handler returns an error to prevent this from leading to a change being delivered.
> Fix TestHTTPTransportWatchConfigContextCancelled

- CHANGELOG.asciidoc
- metrics_test.go
- tracer.go
- tracer_test.go
- transaction_test.go
- validation_test.go
All options should be set at construction time, and should be immutable there on.
This used to be safe when the Tracer did not actively make requests to APM Server until events were enqueued, but this is no longer the case.
> Unexport all of Tracer's fields

- CHANGELOG.asciidoc
- config.go
- docs/configuration.asciidoc
- env_test.go
- tracer.go
Reverts elastic/apm-agent-go#1231
From the spec:
> If possible, agents SHOULD detect sensible defaults for service.name and service.version. In any case agents MUST include service.name - if discovering it is not possible then the default value: unknown-${service.agent.name}-service MUST be used.
We were already doing the first bit ("detect sensible defaults") for service.name, so the fallback is not necessary. It's only necessary to use `unknown-${service.agent.name}-service` if a "sensible default" cannot be detected.
> Revert "use updated default service name"

- tracer.go
- tracer_test.go
Fix a race in DefaultTracer which could lead to two tracers being created, one of which would be closed.
We must hold the write lock while creating the default tracer, checking again that it was not set after releasing the read lock.
Fixes #1247
> apm: fix race in DefaultTracer

- config.go
- config_test.go
- span_test.go
- transaction_test.go
As per the updated span compression specs:
1. Disables same kind compression by default
2. Enable exact match compression by default
Closes #1229
> Disable same kind, enable exact match compression by default

- .github/workflows/addToAPMProject.yml
Add all newly created issues to the APM project board, labeled with team `server` to ensure we keep track of issues in our planned work. 
The script is copied from the [APM Server workflow](https://github.com/elastic/apm-server/blob/main/.github/workflows/add-to-apm-project.yml).
> scripts: add workflow to add to APM github project

- model/marshal_fastjson.go
- model/model.go
Allows the APM Lambda extension to generate and populate the `faas.*` fields for each of the metricsets by modifying the APM model.
This PR is directly related to https://github.com/elastic/apm-aws-lambda/pull/220 (details and test plan are included)
> Add Faas fields to metricset model

- module/apmechov4/middleware.go
Adding a span name option to echo apm middleware such as the one apmhttp has
> Added span request name option to echo tracer

- model/marshal_fastjson.go
- model/model.go
- modelwriter.go
- span.go
- span_test.go
- tracecontext.go
- transaction.go
- transaction_test.go
This is an attempt to implement the Span Links API, mostly inspired by other PRs to the other agents and the spec/docs for OT.
Closes https://github.com/elastic/apm-agent-go/issues/1243
> feat: implement Span Links API

- module/apmawssdkgo/session.go
- module/apmawssdkgo/session_test.go
In the case where a span is dropped in the "build" hook, we don't add the span to the request context. Subsequently, the "send" and "complete" hooks attempt to fetch the span from context, and modify and end it. This can have two negative outcomes:
- a panic will occur if there are no other spans in the context
- if there are other spans in the context, then they will be modified/ended instead of the AWS span that was dropped
I've changed the code to add another context key for the AWS span. The hooks use this instead of `apm.SpanFromContext`.
Fixes https://github.com/elastic/apm-agent-go/issues/1262
> module/apmawssdkgo: fix dropped span handling

- config.go
- config_test.go
- module/apmhttp/handler_test.go
- tracecontext.go
- tracer.go
- transaction.go
- transaction_test.go
Add ELASTIC_APM_TRACE_CONTINUATION_STRATEGY variable to change the
continuation strategy. (Default to 'continue')
Add test to verify trace ids are different and span links are
populated properly.
Closes https://github.com/elastic/apm-agent-go/issues/1221
> feat: implement trace_continuation_strategy

- span.go
- span_test.go
- transaction.go
- transaction_test.go
According to the spec:
If no transaction.type or span.type is provided or the value
is an empty string, the agent needs to set a default value
custom.
Add test to assert the behaviour is compliant to the spec.
Closes https://github.com/elastic/apm-agent-go/issues/1211
> fix: default to custom for empty transaction and span types

- tracecontext.go
When creating a TraceState the entries are parsed and if
we meet an 'es' vendor key we parse the elastic tracestate.
If that happens we can skip the regex key validation to gain
a small performance improvement since the 'es' key is hardcoded
and safe to use.
Benchstat diff:
```
name            old time/op    new time/op    delta
Transaction-16     457ns ± 6%     395ns ± 1%  -13.49%  (p=0.000 n=10+10)
name            old alloc/op   new alloc/op   delta
Transaction-16      194B ± 1%      192B ± 0%   -1.13%  (p=0.000 n=10+10)
name            old allocs/op  new allocs/op  delta
Transaction-16      4.00 ± 0%      4.00 ± 0%     ~     (all equal)
```
To reproduce: `go test -run=NONE -benchmem -bench=BenchmarkTransaction -count=10 .`
> perf: skip tracestate regex validation for es vendor key

- model/marshal_fastjson.go
- model/model.go
- spancontext.go
This should lay the groundwork for backend dependencies granularity.
Different backends have different specs/guidelines and the goal is to replace `SetDestinationService` with `SetServiceTarget` and use the new fields. 
Related to https://github.com/elastic/apm-agent-go/issues/1233  
Related to https://github.com/elastic/apm-agent-go/issues/1267
> feat: add service target fields

- model/model.go
- spancontext.go
According to the spec:
'at least one of those two fields is required to be provided and not empty'
While both are optional, the only one with an explicit clause that
allows empty values is 'type'.
To better reflect that, 'type' is always included (even if empty) and
'name' is omitted if empty.
See https://github.com/elastic/apm/blob/main/specs/agents/tracing-spans-service-target.md
Additionally, unused json tags are removed from internal fields.
> fix: make sure at least one of the service target fields is sent

- module/apmsql/conn.go
- module/apmsql/mysql/mysql_test.go
- module/apmsql/pgxv4/pq_test.go
- module/apmsql/pq/pq_test.go
Sets service target fields for services using the
sql module.
See https://github.com/elastic/apm/blob/main/specs/agents/tracing-instrumentation-db.md#sql-databases
> feat: add service target fields support to sql module

- module/apmazure/queue.go
- module/apmazure/queue_test.go
- module/apmazure/storage.go
Destination resource was 'azurequeue/<AccountName>' but should be
'azurequeue/<QueueName>'.
Span name should be 'AzureQueue <OperationName> to <QueueName>'
but was using the 'AccountName' was being used.
> fix: use the correct destination resource and name for azure queue

- breakdown_test.go
- error.go
- fmt.go
- module/apmgorm/open.go
- module/apmhttp/traceheaders.go
- module/apmot/doc.go
- module/apmzerolog/stack.go
- span_compressed.go
- tracecontext.go
Go 1.19 adds some changes to doc comments:
https://go.dev/doc/go1.19#go-doc
This breaks the Go 1.x ci job.
Reformat code accordingly
> fix: reformat code with go 1.19 to fix ci failure 

- module/apmawssdkgo/sqs_test.go
Assert 'span.name' and 'span.action' are following the
spec for delete_batch operations.
The actions were not described in the original spec but
the output seems to be correct so we just add a test to
avoid regressions and verification.
Closes https://github.com/elastic/apm-agent-go/issues/1170
> test: add testcase for sqs delete_batch operation

- internal/apmhostutil/container_linux.go
- internal/apmhostutil/container_linux_test.go
update k8s pod ID discovery regex to the current status of the spec.
See https://github.com/elastic/apm/blob/main/specs/agents/metadata.md#containerkubernetes-metadata
Add a testcase to make sure the pod mentioned in the related issue is
discovered correctly.
Closes https://github.com/elastic/apm-agent-go/issues/822
> fix: expand k8s pod discovery regex

- module/apmawssdkgo/sns.go
- module/apmawssdkgo/sns_test.go
'span.name' is correctly updated to 'SNS PUBLISH to <specific-name>'.
'TargetArn' is parsed and the endpoint UUID is excluded from the
'span.name'.
Add support for 'PhoneNumber' (note that the actual phone number is
not stored.)
See https://github.com/elastic/apm/blob/main/specs/agents/tracing-instrumentation-aws.md#sns-aws-simple-notification-service
Add more test cases to increase coverage.
Closes https://github.com/elastic/apm-agent-go/issues/1004
> feat: update sns span.name to reflect the current spec

- CHANGELOG.asciidoc
- config.go
- tracer.go
This patch removes the `globalLabel` variable and one-time parsing of
the global labels, in favor of parsing the global labels individually
on tracer construction. This has the advantage that tracers that are
created after start-up will parse environment variables at that time
and not only when the `apm` package is imported.
Encountered while writing a systemtest for elastic/apm-server#8139.
> tracer: Parse global labels per tracer

- internal/apmhostutil/container_linux_test.go
Ubuntu cgroup was returning a false positive container.id:
1:name=systemd:/user.slice/user-1000.slice/user@1000.service/apps.slice/apps-org.gnome.Terminal.slice/vte-spawn-75bc72bd-6642-4cf5-b62c-0674e11bfc84.scope
container.id | spawn-75bc72bd-6642-4cf5-b62c-0674e11bfc84
Add a test to verify the line is not returning a false positive
container ID. This is consistent with what other agents are doing
(e.g. the java agent).
Closes https://github.com/elastic/apm-agent-go/issues/776
> test: verify Ubuntu cgroup line parsing for container ID

- CHANGELOG.asciidoc
- config.go
- config_test.go
- docs/configuration.asciidoc
- env_test.go
- span.go
- span_test.go
- tracer.go
- tracer_test.go
- transaction.go
rename the property and update the handling of special
values like 0 and negative values according to the spec.
Closes https://github.com/elastic/apm-agent-go/issues/1142
> feat: rename span_frames_min_duration to span_stack_trace_min_duration

- config.go
- docs/configuration.asciidoc
- env_test.go
We cannot remove a config option right away as that's a breaking change
and it would create issue for older agents updating.
Add a deprecation notice to the config doc and add the old option as fallback.
> fix: readd deprecated span_frames_min_duration option as fallback for older configuration

- docs/troubleshooting.asciidoc
+ fixes the env flag for log level in docs.
> docs: update correct env flag for loglevel

- module/apmelasticsearch/client.go
- module/apmelasticsearch/client_test.go
- module/apmelasticsearch/internal/integration/elastic_integration_test.go
- module/apmelasticsearch/internal/integration/olivere_integration_test.go
Closes https://github.com/elastic/apm-agent-go/issues/1306
> apmelasticsearch: don't use Host for cluster name

- span.go
- span_test.go
- spancontext.go
This is the final step for complete service target fields
support. Exit spans will fallback to type and subtype similar
to what the deprecated destination resource was doing.
Assertions have been added to tests to verify the service target
type is not overwritten if previously set and that the fallback
mechanism is working properly.
related to https://github.com/elastic/apm-agent-go/pull/1276
Closes https://github.com/elastic/apm-agent-go/pull/1294
> feat: add fallback service target type for exit spans

- module/apmelasticsearch/client.go
- module/apmelasticsearch/client_test.go
- module/apmelasticsearch/clustername.go
- module/apmelasticsearch/internal/integration/elastic_integration_test.go
- module/apmelasticsearch/internal/integration/olivere_integration_test.go
Follow on from https://github.com/elastic/apm-agent-go/pull/1309
Fix extraction of cluster name from `X-Found-Handling-Cluster` header by pulling from response headers rather than request headers.
If the response header is not present, query the nodes API and extract the `cluster_name` field from the response body. This is cached in an LRU (with a fixed size of 100), keyed by the `Host` request header. We cache failures, and there is currently no retrying.
Closes https://github.com/elastic/apm-agent-go/issues/1310
> apmelasticsearch: query ES for cluster name

- module/apmgin/middleware.go
- module/apmgin/middleware_test.go
If gin middleware catches a panic it bypasses other middleware panic handlers. This is an issue in our use case because we have middleware which sends panics to our notification/alert system. The changes in this PR is modeled from other modules which support `panicPropagation`.
> feat: add panic propagation option to gin middleware

- internal/apmhostutil/container_linux.go
- internal/apmhostutil/container_linux_test.go
Update pod UID regexp to support ECS/Fargate containers.
Add testcase to validate the feature.
Closes https://github.com/elastic/apm-agent-go/issues/1303
> feat: add support for ECS/Fargate pod UIDs

- span.go
- span_test.go
Do not silently drop child spans of exit spans. The spec allows for exit spans to have child spans if they have the same type and subtype. One example of this is http trace requests being child spans of an exit span.
Update exit span test to make sure the feature is working as intended.
Closes https://github.com/elastic/apm-agent-go/issues/1319
> fix: allow exit spans to have child spans with the same type and subtype

- apmtest/withtransaction.go
- module/apmawssdkgo/session.go
- module/apmazure/storage.go
- module/apmelasticsearch/client.go
- module/apmgocql/apmgocql_test.go
- module/apmgocql/observer.go
- module/apmgopg/hook.go
- module/apmgopgv10/hook.go
- module/apmgormv2/apmgorm_test.go
- module/apmgrpc/client.go
- module/apmgrpc/client_test.go
- module/apmhttp/client.go
- module/apmhttp/client_test.go
- module/apmhttp/clienttrace.go
- module/apmmongo/monitor.go
- module/apmmongo/monitor_test.go
- module/apmredigo/conn.go
- module/apmsql/apmsql_test.go
- module/apmsql/conn.go
- span.go
Exit spans are spans that describe a call to an external service, such as an outgoing HTTP request or a call to a database.
Marking a span as an exit span also triggers service target fields and destination fields inference.
Update tests to reflect the new fields.
Disable compression in some tests as exit spans can be aggregated based on certain fields, leading to unexpected results.
Additionally, make sure exit spans are not being used as parents of other spans as that would cause the spans to be dropped.
Closes https://github.com/elastic/apm-agent-go/issues/1315
> fix: mark spans representing calls to external services as exit spans

- module/apmredigo/conn.go
- module/apmredigo/conn_test.go
Specific calls (DoWithTimeout) were not being marked as exit spans, as opposed to normal calls.
Add span options and mark the span as exit span.
> fix(apmredigo): mark calls with timeout as exit spans

- module/apmsql/driver.go
The first connect span from the driver connector was not being marked as an exit span.
Add span options and mark it as exit span like the other spans for external services
> fix(apmsql): mark connect span as exit span

- CHANGELOG.asciidoc
- config.go
- docs/configuration.asciidoc
- internal/wildcard/matcher_test.go
Update sanitization rule to ignore *principal* headers by default. Update documentation with the new default values.
Mostly related to Azure SSO and potential exposure of PII.
Closes https://github.com/elastic/apm-agent-go/issues/1316
Spec: https://github.com/elastic/apm/pull/680
> feat: ignore *principal* headers by default

- docs/upgrading.asciidoc
APM Agents are listed now in the central EOL policy table: https://www.elastic.co/support/eol
> EOL table has been moved to central EOL Policy page

- module/apmgocql/apmgocql_test.go
- module/apmgocql/observer.go
- module/apmgoredis/client.go
- module/apmgoredis/client_test.go
- module/apmgoredis/integration_test.go
- module/apmgorm/apmgorm_test.go
- module/apmgorm/context.go
- span.go
- span_test.go
Also, note a bug in Span.End() when ending a child of an exit span.
Relates to https://github.com/elastic/apm-agent-go/issues/1315
> Mark some more spans as exit spans

- docs/instrumenting.asciidoc
https://www.elastic.co/guide/en/apm/agent/go/current/index.html currently renders as:
with `module/apmpgx` at the top level in the navigation.  This should restore the instrumentation navigation expected in the docs
> restore instrumentation nav

- docs/instrumenting.asciidoc
This will backport the following commits from `main` to `2.x`:
- [indent new apmpgx docs (#1371)](https://github.com/elastic/apm-agent-go/pull/1371)
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)
> [2.x] indent new apmpgx docs (#1371)

- .ci/update-specs.yml
- .github/workflows/opentelemetry.yml
- .github/workflows/update-specs.yml
Moves the update specs workflow from apm-server to the consumer using updatecli to have a "dependabot"-like experience.
```
GITHUB_TOKEN=<token>\
GIT_USER=<username> \
GIT_EMAIL=j<email> \
updatecli diff -c .ci/update-specs.yml
```
- https://github.com/elastic/observability-robots/issues/1516
> Add update-specs updatecli workflow

- .github/workflows/ci.yml
The integration/coverage tests don't necessarily run with all Go versions, nor do precheck Makefile targets. Use the "stable" Go version for these jobs to avoid failures like in https://github.com/elastic/apm-agent-go/actions/runs/4267287201/jobs/7428720621.
> .github: run precheck & coverage with 'stable' go

- error.go
- error_go120_test.go
Support Go 1.20's `Unwrap []error` interface, implemented by errors created with `errors.Join`. If this interface is implemented, then the results of `Unwrap` are added as error causes.
> Add support for `Unwrap []error`

- docs/configuration.asciidoc
Update doc to changes in https://github.com/elastic/apm-agent-go/pull/1256 - seems those changes weren't updated in the doc.
> Fix doc around span compression 

- docs/configuration.asciidoc
The Kibana endpoint is no longer required for APM agent central configuration.
For https://github.com/elastic/apm-server/issues/9982.
> docs: remove `kibana.enabled` requirement

- .github/workflows/ci.yml
- scripts/genmod/go.mod
- scripts/genmod/go.sum
- scripts/genmod/main.go
We have some modules (such as apmotel) that don't support all the versions we provide support for.
For example, OpenTelemetry follows the [go release policy](https://go.dev/doc/devel/release), so versions lower than 1.19 aren't supported, and generics are used.
This means we can't build that module on go 1.15, and can't run `make update-modules`.
With this change, we will try to upgrade the go version if it's lower than the one specified. However, if it's higher, we consider that to be on purpose, and don't change it.
> Only upgrade go version in genmod, don't downgrade

- module/apmotel/span.go
- module/apmotel/span_test.go
- module/apmotel/tracer_provider.go
- module/apmotel/tracer_provider_config.go
- module/apmotel/tracer_provider_config_test.go
As I was digging through traces generated by this module, I would have wanted to see attributes set by it to identify where the traces were coming from. But I only was able to know the agent was sending them.
So this adds support for resources, as supported in the official OpenTelemetry SDK, which allows setting custom attributes on all spans.
By default, the following attributes are set:
* `service.name`: `unknown_service:<executable name>`
* `telemetry.sdk.language`: `go`
* `telemetry.sdk.name`: `apmotel`
* `telemetry.sdk.version`: `apm.AgentVersion`
This closely matches the default resource from the official SDK: https://github.com/open-telemetry/opentelemetry-go/blob/main/sdk/resource/resource.go#L203
> Otel Module: handle resources

- module/apmotel/tracer.go
- module/apmotel/tracer_test.go
Right now, we always send an empty TraceContext in spans, making it invalid (it needs a Trace ID and Span ID to be valid), and breaking propagation.
See https://github.com/open-telemetry/opentelemetry-go/blob/main/propagation/trace_context.go#LL48C8-L48C41
With this change, the Trace Context now properly includes both data, and is valid, which would allow distributed tracing properly.
> Set the proper trace ID and span ID in trace context

- module/apmotel/tracer.go
- module/apmotel/tracer_test.go
We need to properly handle traceflags in the context when creating transactions and spans that come from distributed services, or everything is considered as unsampled (and we don't get any data if there is a remote context).
> Handle context flags when creating remote transactions and spans

- internal/apmgodog/go.mod
- internal/tracecontexttest/go.mod
- module/apmelasticsearch/internal/integration/go.mod
- scripts/genmod/go.mod
- scripts/genmod/main.go
Existing `make update-modules` is not updating non public modules. Fix that by removing the non public module filter in genmod. After the fix, all non public modules go.mod should also reference the latest go agent version.
> Fix update-modules not updating non public modules

- module/apmotel/tracer.go
- module/apmotel/tracer_test.go
- module/apmotel/wrapper.go
- module/apmotel/wrapper_test.go
Closes #1449 
We didn't store the agent span/transaction into the context, as that doesn't happen automatically and requires a manual operation when using the agent directly.
When using otel, which does add it to every context, it makes more sense not to have to require folks to do that themselves though.
This also sets up a context wrapper in the agent, so spans created from the agent are stored in the context to be read by otel.
> Allow retrieving span created in agent from otel, and store agent span in context when creating it with otel

- spancontext.go
If an HTTP client is instrumented with apmhttp, then the http.Request.URL is recorded for including in span context. The caller of the HTTP client request may mutate the URL after the response is ready, so we must clone the URL while recording it to prevent data races.
> Fix data race accessing Request.URL

- README.md
- docs/supported-tech.asciidoc
The survey itself is rather outdated, and has served its purpose. Send users to the Discuss forum instead.
> Remove survey link

- CHANGELOG.asciidoc
- README.md
- docs/set-up.asciidoc
* docs: update doc with go support policy
* docs: remove go.mod comment
the doc doesn't actually mention specific versions
> [2.x]  docs: update doc with go support policy (Backport #1488)

- docs/configuration.asciidoc
if i understand correctly the default value is "auto"
https://github.com/elastic/apm-agent-go/blob/main/utils.go#L179
> update default value of ELASTIC_APM_CLOUD_PROVIDER in doc

- SECURITY.md
Align security policy with other repositories
Mention the public bug bounty program.
UPDATE: after looking into this, it seems other repositories are using the org-wide security policy from the health files repo. Remove the custom SECURITY.md to fallback to that.
>  docs: remove SECURITY.md to fallback to org-wide security policy

- .ci/updatecli.d/update-json-specs.yml
Removing the newly introduced tests for `container_metadata_discovery.json` until changes from https://github.com/elastic/apm/pull/807 are implemented.
> Remove container_metadata_discovery from tests

- docs/instrumenting.asciidoc
Per Elastic docs websites' feedback, changes elastic domain from ".com" to ".co" to match other examples.
> [DOC+] Change example from elastic.com to elastic.co

- docs/logs.asciidoc
This PR cherry-picks https://github.com/elastic/apm-agent-go/pull/1506 to `2.x`.
> [2.x] Fix documentation bugs

- module/apmotel/span.go
- module/apmotel/span_test.go
Currently, if we try closing a span twice, we will handle the close both times. However, the agent deletes `SpanData` on the first close, so we cannot set span data anymore.
Closes #1490.
> apmotel: disallow closing spans twice

- .github/workflows/microbenchmark.yml
- scripts/ci/bench.sh
- scripts/ci/setenv.sh
uses the script from https://github.com/elastic/beats/blob/024a9cec6608c6f371ad1cb769649e024124ff92/.ci/scripts/install-go.sh
`gimme` is not much maintained these days and 1.21 is not supported as per https://github.com/travis-ci/gimme/issues/210
I ran this [build ](https://buildkite.com/elastic/apm-agent-microbenchmark/builds/1002#018ba3c0-89a0-459f-bdf0-cccb4cd184a9) manually (it can only be accessed by Elastic) and so far it installed go using https://github.com/andrewkroh/gvm
> ci: use gvm instead of gimme 

- .github/workflows/labeler.yml
The labeler needs to have the `pull-request: write` permission, so it can assign labels on PRs.
See https://github.com/elastic/apm-agent-go/actions/runs/8246861649/job/22553967383?pr=1580
> Add write permission to labeler job

- docs/instrumenting.asciidoc
As reported in https://github.com/elastic/apm-agent-go/pull/1569#issuecomment-1999315749
> Add apm/sqlserver module to apmsql doc

- README.md
- docs/set-up.asciidoc
> Specify `go get` needs to run within go modules

- internal/apmschema/jsonschema/metadata.json
APM agent json server schema automatic sync
*Changeset*
* https://github.com/elastic/apm-data/pull/255
* https://github.com/elastic/apm-data/commit/a76e999543efb3ba803c9a57dd13a4f6b3ffa7e1
---
<Actions>
<action id="e6053744e64b539ede7437649ecf7d637913c0598fb171b92bce658f36886c7c">
<h3>update-specs</h3>
<details id="fa450b1827de4f90bb214eaf9924527a95b821d8f72de0b38a8f5b75ac6dcdc2">
<summary>APM agent json server schema a76e999543efb3ba803c9a57dd13a4f6b3ffa7e1</summary>
<p>ran shell command &#34;tar -xzf /home/runner/work/apm-agent-go/apm-agent-go/json-schema.tgz &amp;&amp; git --no-pager diff&#34;</p>
</details>
<a href="https://github.com/elastic/apm-agent-go/actions/runs/8579173581">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
<td width="77">
</td>
<td>
<p> …
> [Automation] Update JSON server schema specs

- internal/tracecontexttest/Dockerfile-harness
Follow snyk suggestion and update docker image to mitigate CVE-2024-8805.
> CVE-2024-8805 - update docker image

- .github/workflows/addToAPMProject.yml
Reverts elastic/apm-agent-go#1660
I need to find out why the permission is not correct... hence, I prefer to revert until I figure out what's going on
See https://github.com/elastic/apm-agent-go/actions/runs/11216690372
```
Error: Could not create installation access token.
at createInstallationAccessToken (file:///home/runner/work/_actions/tibdex/github-app-token/3beb63f4bd073e61482598c45c71c1019b59b73a/dist/main/index.js:9:86267)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async file:///home/runner/work/_actions/tibdex/github-app-token/3beb63f4bd073e6[14](https://github.com/elastic/apm-agent-go/actions/runs/11216690372/job/31176542839#step:2:15)82598c45c71c1019b59b73a/dist/main/index.js:9:87518
at async run …
```
> Revert "github-actions: use GH app to manage the projects"

- .github/workflows/addToAPMProject.yml
I somehow used the wrong permissions set in https://github.com/elastic/apm-agent-go/pull/1660
I tested it in my playground, and it worked as [expected](https://github.com/orgs/elastic/projects/629/views/1?filterQuery=test+add+project+6+&pane=issue&itemId=82591771&issue=elastic%7Cobservability-robots-playground%7C83)
> github-actions: use ephemeral tokens with the right permissions

- .github/workflows/ci.yml
> the macOS 12 runner image will be removed by December 3rd, 2024
I guess we can use `latest` as we normally are using the latest OS version
> ci: use macos-latest

- .github/workflows/microbenchmark.yml
dependabot does not bump version for githubactions using semver and 'v1', see https://github.com/dependabot/dependabot-core/issues/10924
> github-actions: use v1 for the oblt-actions

- .github/workflows/updatecli.yml
Fix the version to be used to the latest one for now
Otherwise, https://github.com/elastic/apm-agent-go/pull/1671 won't work
🐔 🥚  since https://github.com/updatecli/updatecli/releases/tag/v0.86.0
> Sources were always executed before conditions and then targets.
With this change, sources, conditions, and targets can now depend on any other resource type to allow an advanced update scenario.
And there are errors like
```
target: target#agent-json-specs
-----------------------
**Dry Run enabled**
The shell 🐚 command "/bin/sh /tmp/updatecli/bin/68b2939c124c411192667268d8f6edefbaa79f085494796eb8122c21afdb37bf.sh" exited on error (exit code 2) with the following output:
----
----
command stderr output was:
----
tar (child): /home/runner/work/apm-agent-go/apm-agent-go/json-specs.tgz: Cannot …
```
> ci: support updatecli version required for the new oblt updatecli policies

- error.go
- error_test.go
We sometimes see Buildkite fail to add annotations to a build and when this happens, it fails with the following error:
```
{"log.level":"error","ecs.version":"1.6.0","gobld.version":"7.25.2","gobld.gitCommit":"8eae7d1","error.message":"Message: An error occurred while executing your GraphQL query. Please contact hello@buildkite.com for help and provide this query in the email., Locations: [], Extensions: map[], Path: []","error":[{"message":"An error occurred while executing your GraphQL query. Please contact hello@buildkite.com for help and provide this query in the email.","extensions":null,"locations":null,"path":null}],"@timestamp":"2024-11-22T20:25:12.306Z","log.origin":{"file.name":"/go/src/gobld/buildkite/buildkite.go","file.line":157},"trace.id":"d9ab02ae11e462233dfbcdb189fc043a", …
```
> Avoid `nil` values when unwrapping errors

- .github/workflows/ci.yml
This check has been failing for months.
Its usefulness is also very limited, as the coverage results aren't sent anywhere, they're only displayed in the log output, making the data impossible to use in the current state.
> Remove coverage ci check

- Makefile
This should prevent the CI from failing randomly.
> Fix random precheck failures

- docs/reference/log-correlation.md
Related to https://github.com/elastic/elasticsearch/pull/125663
Removes reliance on temporary redirects in the elasticsearch repo.
> [docs] Remove reliance on temporary redirects

- docs/reference/api-documentation.md
- docs/reference/configuration.md
- docs/reference/index.md
- docs/reference/log-correlation.md
- docs/reference/upgrading.md
Related to https://github.com/elastic/docs-content/pull/1069
Updates links to APM, Synthetics, and Uptime pages in elastic/docs-content.
> [docs] Update APM, Synthetics, Uptime links
